export interface RegulationData {
  code: string
  short_name: string
  name: string
  regions: string[]
  industries: string[] | null   // null = all industries
  jurisdiction: string
  authority: string | null
  type: 'privacy' | 'security' | 'sector'
  summary: string
  max_fine: string | null
  effective_date: string | null // ISO YYYY-MM-DD
  requirements: RequirementData[]
}

export interface RequirementData {
  article: string
  title: string
  description: string
  dlp_relevance: string
  fine: string | null
  severity: 'critical' | 'high' | 'medium'
  dlp_controls: string[]
}

export const REGULATIONS: RegulationData[] = [
  // ── Europe ──────────────────────────────────────────────────────────────────
  {
    code: 'gdpr',
    short_name: 'GDPR',
    name: 'General Data Protection Regulation',
    regions: ['EU', 'EEA'],
    industries: null,
    jurisdiction: 'European Union',
    authority: 'Data Protection Authorities (supervisory authorities per member state)',
    type: 'privacy',
    summary: 'The EU\'s primary data protection law governing the collection, processing, and transfer of personal data of EU/EEA residents. Applies globally to any organisation handling EU/EEA personal data.',
    max_fine: '€20M or 4% of global annual turnover (whichever is higher)',
    effective_date: '2018-05-25',
    requirements: [
      {
        article: 'Article 5(1)(f)',
        title: 'Integrity and Confidentiality',
        description: 'Personal data must be processed in a manner that ensures appropriate security, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage.',
        dlp_relevance: 'DLP directly enforces this principle by preventing unauthorised data exfiltration across all channels (web, email, endpoint, SaaS).',
        fine: '€20M or 4% of global annual turnover',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'dlp_saas'],
      },
      {
        article: 'Article 25',
        title: 'Data Protection by Design and by Default',
        description: 'Controllers must implement appropriate technical and organisational measures to integrate data protection principles into processing activities by design and by default.',
        dlp_relevance: 'DLP policies must be built into systems from the start — not bolted on. Data classification and access controls are the foundation of privacy-by-design.',
        fine: '€10M or 2% of global annual turnover',
        severity: 'high',
        dlp_controls: ['data_classification', 'access_controls', 'dlp_saas'],
      },
      {
        article: 'Article 32',
        title: 'Security of Processing',
        description: 'Controllers and processors must implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including encryption, pseudonymisation, and ongoing confidentiality.',
        dlp_relevance: 'The core technical obligation. DLP tools are a primary mechanism for meeting Art. 32 — covering encryption in transit, access controls, and preventing unauthorised disclosure.',
        fine: '€10M or 2% of global annual turnover',
        severity: 'critical',
        dlp_controls: ['dlp_web', 'dlp_email', 'dlp_endpoint', 'dlp_saas', 'genai_controls', 'encryption_transit', 'access_controls'],
      },
      {
        article: 'Article 33',
        title: 'Notification of Personal Data Breach',
        description: 'In the event of a personal data breach, the controller must notify the relevant supervisory authority within 72 hours of becoming aware of it, unless unlikely to result in risk.',
        dlp_relevance: 'DLP alerting and audit logging are the detection mechanism. Without them, organisations cannot identify breaches in time to meet the 72-hour notification window.',
        fine: '€10M or 2% of global annual turnover',
        severity: 'critical',
        dlp_controls: ['audit_logging', 'breach_detection'],
      },
      {
        article: 'Article 34',
        title: 'Communication of Breach to Data Subject',
        description: 'When a breach is likely to result in high risk to individuals, the controller must communicate the breach to affected data subjects without undue delay.',
        dlp_relevance: 'DLP breach detection identifies the scope of a breach (which data, which individuals), enabling accurate communication to affected data subjects.',
        fine: '€20M or 4% of global annual turnover',
        severity: 'high',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
    ],
  },

  {
    code: 'uk_gdpr',
    short_name: 'UK GDPR',
    name: 'UK General Data Protection Regulation',
    regions: ['UK'],
    industries: null,
    jurisdiction: 'United Kingdom',
    authority: 'Information Commissioner\'s Office (ICO)',
    type: 'privacy',
    summary: 'The UK\'s post-Brexit data protection law, retained from EU GDPR with UK-specific modifications. Applies to organisations processing personal data of UK residents.',
    max_fine: '£17.5M or 4% of global annual turnover (whichever is higher)',
    effective_date: '2021-01-01',
    requirements: [
      {
        article: 'Article 5(1)(f)',
        title: 'Integrity and Confidentiality',
        description: 'Personal data must be processed securely to protect against unauthorised processing and accidental loss or damage.',
        dlp_relevance: 'Same as EU GDPR — DLP enforces the integrity and confidentiality principle across all data channels.',
        fine: '£17.5M or 4% of global annual turnover',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'dlp_saas'],
      },
      {
        article: 'Article 32',
        title: 'Security of Processing',
        description: 'Appropriate technical and organisational measures must be implemented to ensure data security, including encryption and ongoing confidentiality.',
        dlp_relevance: 'DLP is a primary technical measure for meeting the security of processing obligation under UK GDPR.',
        fine: '£10M or 2% of global annual turnover',
        severity: 'critical',
        dlp_controls: ['dlp_web', 'dlp_email', 'encryption_transit', 'access_controls', 'genai_controls'],
      },
      {
        article: 'Article 33',
        title: 'Breach Notification (72-hour)',
        description: 'Notify the ICO within 72 hours of becoming aware of a personal data breach.',
        dlp_relevance: 'DLP audit logs provide the evidence trail needed to identify breach timing and scope for ICO notification.',
        fine: '£17.5M or 4% of global annual turnover',
        severity: 'critical',
        dlp_controls: ['audit_logging', 'breach_detection'],
      },
      {
        article: 'ICO Guidelines',
        title: 'Accountability and Governance',
        description: 'Organisations must demonstrate compliance, maintain records of processing activities, and implement appropriate data governance frameworks.',
        dlp_relevance: 'DLP audit trails and classification policies are key evidence of accountability to the ICO.',
        fine: '£8.75M or 2% of global annual turnover',
        severity: 'high',
        dlp_controls: ['data_classification', 'audit_logging'],
      },
    ],
  },

  {
    code: 'nis2',
    short_name: 'NIS2',
    name: 'Network and Information Security Directive 2',
    regions: ['EU'],
    industries: ['critical_infrastructure', 'energy', 'transport', 'financial', 'healthcare', 'digital_infrastructure'],
    jurisdiction: 'European Union',
    authority: 'National Competent Authorities (per member state)',
    type: 'security',
    summary: 'EU directive requiring essential and important entities to implement cybersecurity risk management measures and report significant incidents. Expands the scope of the original NIS Directive significantly.',
    max_fine: '€10M or 2% of global annual turnover (essential entities); €7M or 1.4% (important entities)',
    effective_date: '2024-10-17',
    requirements: [
      {
        article: 'Article 21(2)(b)',
        title: 'Incident Handling',
        description: 'Entities must have policies and procedures for handling cybersecurity incidents, including detection, containment, and recovery.',
        dlp_relevance: 'DLP breach detection and audit logging are core to incident detection and response capabilities required by NIS2.',
        fine: '€10M or 2% of global annual turnover',
        severity: 'critical',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
      {
        article: 'Article 21(2)(d)',
        title: 'Supply Chain Security',
        description: 'Security in supply chain relationships, including security aspects concerning the relationships between each entity and its direct suppliers or service providers.',
        dlp_relevance: 'DLP controls on SaaS applications and data sharing with third parties directly address supply chain data security.',
        fine: '€10M or 2% of global annual turnover',
        severity: 'high',
        dlp_controls: ['dlp_saas', 'data_classification', 'access_controls'],
      },
      {
        article: 'Article 21(2)(h)',
        title: 'Access Control and Human Resources Security',
        description: 'Access control policies including need-to-know, multi-factor authentication, and human resources security measures.',
        dlp_relevance: 'DLP access controls and data classification enforce need-to-know principles across all data channels.',
        fine: '€10M or 2% of global annual turnover',
        severity: 'high',
        dlp_controls: ['access_controls', 'data_classification', 'dlp_endpoint'],
      },
      {
        article: 'Article 21(2)(a)',
        title: 'Risk Analysis and Security Policies',
        description: 'Risk analysis and information system security policies covering all aspects of cybersecurity risk management.',
        dlp_relevance: 'DLP gap assessments feed directly into the risk analysis required under NIS2 for data exfiltration risks.',
        fine: '€10M or 2% of global annual turnover',
        severity: 'high',
        dlp_controls: ['data_classification', 'audit_logging'],
      },
    ],
  },

  {
    code: 'dora',
    short_name: 'DORA',
    name: 'Digital Operational Resilience Act',
    regions: ['EU'],
    industries: ['financial'],
    jurisdiction: 'European Union',
    authority: 'European Supervisory Authorities (EBA, EIOPA, ESMA)',
    type: 'sector',
    summary: 'EU regulation requiring financial entities to manage ICT risks, test resilience, report ICT incidents, and manage third-party ICT risks. Applies to banks, insurance companies, investment firms, and critical ICT providers.',
    max_fine: 'Up to 1% of average daily worldwide turnover for up to 6 months (for ICT third-party providers)',
    effective_date: '2025-01-17',
    requirements: [
      {
        article: 'Article 9',
        title: 'Protection and Prevention',
        description: 'Financial entities must put in place ICT security policies, procedures and tools to ensure the protection of ICT assets from cyberattacks.',
        dlp_relevance: 'DLP tools are a primary protection measure for preventing data exfiltration and insider threats within financial entities.',
        fine: 'Supervisory measures and periodic penalty payments',
        severity: 'critical',
        dlp_controls: ['dlp_web', 'dlp_email', 'dlp_endpoint', 'dlp_saas', 'access_controls'],
      },
      {
        article: 'Article 10',
        title: 'Detection',
        description: 'Financial entities must have mechanisms for promptly detecting anomalous activities including ICT network performance issues and ICT-related incidents.',
        dlp_relevance: 'DLP anomaly detection and audit logging are core detection mechanisms for data-related ICT incidents.',
        fine: 'Supervisory measures',
        severity: 'high',
        dlp_controls: ['audit_logging', 'breach_detection'],
      },
      {
        article: 'Article 8',
        title: 'ICT Asset Management',
        description: 'Financial entities must identify, classify and document all ICT assets, including those that support critical or important functions.',
        dlp_relevance: 'Data classification is fundamental to ICT asset management — knowing what data exists and where it flows.',
        fine: 'Supervisory measures',
        severity: 'high',
        dlp_controls: ['data_classification'],
      },
      {
        article: 'Article 17',
        title: 'ICT-Related Incident Management',
        description: 'Financial entities must establish and implement ICT-related incident management processes for detecting, managing, and notifying ICT-related incidents.',
        dlp_relevance: 'DLP breach detection and audit logging are the first line of incident detection for data-related breaches.',
        fine: 'Supervisory measures',
        severity: 'critical',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
    ],
  },

  // ── India ────────────────────────────────────────────────────────────────────
  {
    code: 'dpdp',
    short_name: 'DPDP Act',
    name: 'Digital Personal Data Protection Act 2023',
    regions: ['India'],
    industries: null,
    jurisdiction: 'India',
    authority: 'Data Protection Board of India',
    type: 'privacy',
    summary: 'India\'s primary data protection legislation governing the processing of digital personal data of individuals in India. Applies to organisations processing personal data of Indian residents, both within and outside India.',
    max_fine: '₹250 Crore (~€27M) per violation',
    effective_date: '2023-08-11',
    requirements: [
      {
        article: 'Section 8(4)',
        title: 'Security Safeguards',
        description: 'Data fiduciaries must implement appropriate technical and organisational measures to implement the provisions of the Act and protect personal data in their possession or control.',
        dlp_relevance: 'DLP is a core technical safeguard under DPDP — preventing unauthorised access and exfiltration of personal data.',
        fine: '₹250 Crore per violation',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit', 'access_controls'],
      },
      {
        article: 'Section 8(6)',
        title: 'Personal Data Breach Notification',
        description: 'Data fiduciaries must notify the Data Protection Board and affected data principals in the event of a personal data breach.',
        dlp_relevance: 'DLP breach detection and audit logging enable organisations to identify breaches quickly and gather the evidence needed for Board notification.',
        fine: '₹200 Crore per violation',
        severity: 'critical',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
      {
        article: 'Section 6',
        title: 'Purpose Limitation and Data Minimisation',
        description: 'Personal data must be processed only for the specific, clear, and lawful purpose for which it was collected and not retained beyond the necessary period.',
        dlp_relevance: 'DLP classification policies enforce purpose limitation by controlling where and how different categories of personal data can flow.',
        fine: '₹150 Crore per violation',
        severity: 'high',
        dlp_controls: ['data_classification', 'access_controls', 'dlp_saas'],
      },
      {
        article: 'Section 9',
        title: 'Processing of Children\'s Personal Data',
        description: 'Data fiduciaries must obtain verifiable parental consent before processing personal data of children (under 18) and must not process data harmful to children.',
        dlp_relevance: 'DLP content inspection can detect and block the unauthorised processing or transfer of data tagged as belonging to minors.',
        fine: '₹200 Crore per violation',
        severity: 'high',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_saas'],
      },
    ],
  },

  {
    code: 'rbi_csf',
    short_name: 'RBI CSF',
    name: 'RBI Cybersecurity Framework for Banks',
    regions: ['India'],
    industries: ['financial'],
    jurisdiction: 'India',
    authority: 'Reserve Bank of India (RBI)',
    type: 'sector',
    summary: 'Framework requiring scheduled commercial banks in India to implement a robust cybersecurity policy, incident response, and controls for protecting customer data and critical banking infrastructure.',
    max_fine: 'Regulatory sanctions, penalties, and licence conditions',
    effective_date: '2016-06-02',
    requirements: [
      {
        article: 'Annex I — Controls',
        title: 'Data-at-Rest and Data-in-Transit Protection',
        description: 'Banks must implement encryption and access controls for sensitive customer data both at rest and in transit.',
        dlp_relevance: 'DLP enforces encryption-in-transit policies and prevents unencrypted sensitive banking data from leaving the organisation.',
        fine: 'Regulatory penalty under BR Act',
        severity: 'critical',
        dlp_controls: ['encryption_transit', 'dlp_email', 'dlp_web', 'access_controls'],
      },
      {
        article: 'Section 6 — Incident Response',
        title: 'Cyber Incident Reporting (6-hour rule)',
        description: 'Banks must report cybersecurity incidents to RBI within 2–6 hours of detection, with detailed incident reports within 24 hours.',
        dlp_relevance: 'DLP alerting provides immediate notification of data exfiltration events, enabling banks to meet the RBI\'s strict 6-hour reporting window.',
        fine: 'Regulatory penalty under BR Act',
        severity: 'critical',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
      {
        article: 'Section 4 — Data Classification',
        title: 'Data Classification and Handling',
        description: 'Banks must classify data based on sensitivity and implement controls commensurate with the classification level.',
        dlp_relevance: 'Data classification is the foundation of the RBI framework — all other DLP controls flow from proper classification.',
        fine: 'Regulatory penalty',
        severity: 'high',
        dlp_controls: ['data_classification', 'dlp_endpoint'],
      },
    ],
  },

  {
    code: 'sebi_cscrf',
    short_name: 'SEBI CSCRF',
    name: 'SEBI Cyber Security and Cyber Resilience Framework',
    regions: ['India'],
    industries: ['financial'],
    jurisdiction: 'India',
    authority: 'Securities and Exchange Board of India (SEBI)',
    type: 'sector',
    summary: 'Framework for SEBI-regulated entities (stock exchanges, depositories, brokers, mutual funds) covering cybersecurity governance, risk management, and incident response.',
    max_fine: 'Regulatory action including suspension, cancellation of registration, or monetary penalties',
    effective_date: '2023-08-25',
    requirements: [
      {
        article: 'Section 3 — Controls',
        title: 'Data Leakage Prevention',
        description: 'SEBI-regulated entities must implement DLP solutions to prevent unauthorised disclosure of confidential securities market data.',
        dlp_relevance: 'SEBI explicitly requires DLP implementation as a mandatory control for protecting market-sensitive information (price-sensitive data, insider information).',
        fine: 'Regulatory sanctions',
        severity: 'critical',
        dlp_controls: ['dlp_web', 'dlp_email', 'dlp_endpoint', 'dlp_saas', 'data_classification'],
      },
      {
        article: 'Section 4 — Incident Management',
        title: 'Incident Detection and Reporting',
        description: 'Entities must implement mechanisms to detect, respond to, and report cybersecurity incidents to SEBI within prescribed timeframes.',
        dlp_relevance: 'DLP audit logging and breach detection provide the detection layer required for SEBI incident management.',
        fine: 'Regulatory sanctions',
        severity: 'high',
        dlp_controls: ['audit_logging', 'breach_detection'],
      },
      {
        article: 'Section 2 — Governance',
        title: 'Data Classification and Access Control',
        description: 'Regulated entities must classify data based on sensitivity, implement access controls, and maintain audit trails.',
        dlp_relevance: 'Data classification and access controls are foundational to the SEBI framework — particularly for preventing insider trading data leaks.',
        fine: 'Regulatory sanctions',
        severity: 'high',
        dlp_controls: ['data_classification', 'access_controls', 'audit_logging'],
      },
    ],
  },

  // ── United States ────────────────────────────────────────────────────────────
  {
    code: 'hipaa',
    short_name: 'HIPAA',
    name: 'Health Insurance Portability and Accountability Act',
    regions: ['US'],
    industries: ['healthcare'],
    jurisdiction: 'United States',
    authority: 'U.S. Department of Health and Human Services (HHS) / OCR',
    type: 'sector',
    summary: 'US federal law protecting individually identifiable health information (PHI) held by covered entities and business associates. Sets standards for electronic PHI security and privacy.',
    max_fine: '$100 to $1.9M per violation category per year (up to $1.9M per violation category)',
    effective_date: '1996-08-21',
    requirements: [
      {
        article: '§164.308(a)(1)',
        title: 'Security Management Process',
        description: 'Covered entities must implement policies and procedures to prevent, detect, contain, and correct security violations. Includes risk analysis and risk management.',
        dlp_relevance: 'DLP is a core risk management control under HIPAA — it prevents unauthorised disclosure of PHI and provides evidence for risk analysis.',
        fine: '$100,000 to $1.9M per violation category',
        severity: 'critical',
        dlp_controls: ['data_classification', 'breach_detection', 'audit_logging'],
      },
      {
        article: '§164.312(a)(1)',
        title: 'Access Control',
        description: 'Implement technical policies and procedures for electronic information systems that maintain ePHI to allow access only to authorised persons or software programs.',
        dlp_relevance: 'DLP access controls enforce who can access, copy, or transmit ePHI, preventing both insider threats and accidental disclosure.',
        fine: '$100,000 to $1.9M per violation category',
        severity: 'critical',
        dlp_controls: ['access_controls', 'dlp_endpoint', 'dlp_saas'],
      },
      {
        article: '§164.312(b)',
        title: 'Audit Controls',
        description: 'Implement hardware, software, and/or procedural mechanisms that record and examine activity in information systems that contain or use ePHI.',
        dlp_relevance: 'DLP audit logging is a direct implementation of the HIPAA audit controls requirement, providing full activity trails for ePHI.',
        fine: '$100,000 to $1.9M per violation category',
        severity: 'critical',
        dlp_controls: ['audit_logging'],
      },
      {
        article: '§164.312(c)(1)',
        title: 'Integrity Controls',
        description: 'Implement policies and procedures to protect ePHI from improper alteration or destruction.',
        dlp_relevance: 'DLP prevents unauthorised modification or deletion of ePHI by controlling who can access and manipulate PHI files.',
        fine: '$100,000 to $1.9M per violation category',
        severity: 'high',
        dlp_controls: ['data_classification', 'access_controls', 'dlp_endpoint'],
      },
      {
        article: '§164.312(e)(1)',
        title: 'Transmission Security',
        description: 'Implement technical security measures to guard against unauthorised access to ePHI that is being transmitted over electronic communications networks.',
        dlp_relevance: 'DLP enforces encryption in transit and blocks unencrypted PHI from being transmitted via email, web, or other channels.',
        fine: '$100,000 to $1.9M per violation category',
        severity: 'critical',
        dlp_controls: ['encryption_transit', 'dlp_email', 'dlp_web'],
      },
    ],
  },

  {
    code: 'glba',
    short_name: 'GLBA',
    name: 'Gramm-Leach-Bliley Act (Safeguards Rule)',
    regions: ['US'],
    industries: ['financial'],
    jurisdiction: 'United States',
    authority: 'Federal Trade Commission (FTC) / Federal Banking Regulators',
    type: 'sector',
    summary: 'Requires US financial institutions to protect the security and confidentiality of customer financial information. The FTC Safeguards Rule (updated 2023) mandates a comprehensive information security program.',
    max_fine: '$100,000 per violation for financial institutions; $10,000 per violation for individuals',
    effective_date: '2003-05-23',
    requirements: [
      {
        article: '16 CFR §314.4(c)',
        title: 'Access Controls',
        description: 'Financial institutions must control access to customer information by implementing multi-factor authentication, access limitations, and encryption of customer data.',
        dlp_relevance: 'DLP enforces the access control and encryption requirements for customer financial data across all channels.',
        fine: '$100,000 per violation',
        severity: 'critical',
        dlp_controls: ['access_controls', 'encryption_transit', 'dlp_endpoint'],
      },
      {
        article: '16 CFR §314.4(d)',
        title: 'Encryption of Customer Information',
        description: 'Customer information in transit over external networks or at rest must be encrypted using current cryptographic standards.',
        dlp_relevance: 'DLP enforces encryption-in-transit policies and blocks unencrypted customer financial data from leaving the organisation.',
        fine: '$100,000 per violation',
        severity: 'critical',
        dlp_controls: ['encryption_transit', 'dlp_email', 'dlp_web'],
      },
      {
        article: '16 CFR §314.4(h)',
        title: 'Incident Response Plan',
        description: 'Institutions must establish a written incident response plan to address unauthorized access to or use of customer information.',
        dlp_relevance: 'DLP breach detection is the triggering mechanism for the GLBA incident response plan — it identifies when customer data has been accessed or disclosed without authorisation.',
        fine: '$100,000 per violation',
        severity: 'high',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
      {
        article: '16 CFR §314.4(f)',
        title: 'Monitor and Test',
        description: 'Financial institutions must regularly monitor and test the effectiveness of security controls, including access controls and data protection measures.',
        dlp_relevance: 'DLP testing (via Control Validator) and audit trail review are the monitoring mechanisms required under GLBA.',
        fine: '$100,000 per violation',
        severity: 'high',
        dlp_controls: ['audit_logging', 'breach_detection'],
      },
    ],
  },

  {
    code: 'ccpa',
    short_name: 'CCPA/CPRA',
    name: 'California Consumer Privacy Act / California Privacy Rights Act',
    regions: ['US'],
    industries: null,
    jurisdiction: 'California, United States',
    authority: 'California Privacy Protection Agency (CPPA)',
    type: 'privacy',
    summary: 'California\'s comprehensive privacy law granting consumers rights over their personal information and imposing obligations on businesses that collect, sell, or share consumer personal data. CPRA (2020) strengthened CCPA with a new enforcement agency.',
    max_fine: '$2,500 per unintentional violation; $7,500 per intentional violation; $100–$750 per consumer per incident for data breaches',
    effective_date: '2020-01-01',
    requirements: [
      {
        article: '§1798.81.5',
        title: 'Reasonable Security Measures',
        description: 'Businesses must implement and maintain reasonable security procedures and practices appropriate to the nature of the personal information they collect.',
        dlp_relevance: 'DLP is a cornerstone of "reasonable security" for businesses holding Californian consumer data — covering web, email, endpoint, and SaaS channels.',
        fine: '$100–$750 per consumer per incident',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit'],
      },
      {
        article: '§1798.150',
        title: 'Private Right of Action for Data Breaches',
        description: 'Consumers have a private right of action against businesses for data breaches resulting from failure to implement reasonable security measures.',
        dlp_relevance: 'DLP prevents the data breaches that trigger CCPA/CPRA private litigation — each blocked exfiltration is a prevented lawsuit.',
        fine: '$100–$750 per consumer per incident or actual damages',
        severity: 'critical',
        dlp_controls: ['breach_detection', 'audit_logging', 'dlp_web', 'dlp_email'],
      },
      {
        article: 'CPRA §1798.100(d)',
        title: 'Data Minimisation and Purpose Limitation',
        description: 'Businesses must not collect more personal information than reasonably necessary and must not use personal information for purposes incompatible with the disclosed purpose.',
        dlp_relevance: 'DLP classification policies enforce purpose limitation by controlling data flows and preventing use of consumer data beyond disclosed purposes.',
        fine: '$2,500–$7,500 per violation',
        severity: 'medium',
        dlp_controls: ['data_classification', 'dlp_saas', 'access_controls'],
      },
    ],
  },

  {
    code: 'cmmc',
    short_name: 'CMMC 2.0',
    name: 'Cybersecurity Maturity Model Certification 2.0',
    regions: ['US'],
    industries: ['defence', 'government'],
    jurisdiction: 'United States',
    authority: 'U.S. Department of Defense (DoD)',
    type: 'security',
    summary: 'DoD framework requiring defence contractors and subcontractors to achieve specific cybersecurity certification levels (Level 1, 2, or 3) based on the sensitivity of the data they handle (FCI and CUI).',
    max_fine: 'Loss of DoD contracts; False Claims Act penalties up to $27,894 per false claim',
    effective_date: '2021-11-04',
    requirements: [
      {
        article: 'AC.L2-3.1.3',
        title: 'CUI Flow Control',
        description: 'Control the flow of Controlled Unclassified Information (CUI) in accordance with approved authorisations.',
        dlp_relevance: 'DLP directly implements CUI flow control — the primary control for preventing unauthorised CUI disclosure across all channels.',
        fine: 'Loss of contract eligibility',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'dlp_saas'],
      },
      {
        article: 'AU.L2-3.3.1',
        title: 'Audit Logging',
        description: 'Create and retain system audit logs and records to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorised system activity.',
        dlp_relevance: 'DLP audit logging provides the required audit records for all CUI-related activities and potential incidents.',
        fine: 'Loss of contract eligibility',
        severity: 'critical',
        dlp_controls: ['audit_logging'],
      },
      {
        article: 'MP.L2-3.8.5',
        title: 'Media Sanitisation and Protection',
        description: 'Control access to media containing CUI and sanitise or destroy media before disposal or reuse.',
        dlp_relevance: 'DLP endpoint controls prevent CUI from being copied to removable media and enforce controls over physical data transfer.',
        fine: 'Loss of contract eligibility',
        severity: 'high',
        dlp_controls: ['dlp_endpoint', 'access_controls'],
      },
      {
        article: 'SC.L2-3.13.16',
        title: 'CUI at Rest',
        description: 'Protect the confidentiality of CUI at rest.',
        dlp_relevance: 'DLP classification and access controls ensure CUI is identified and protected wherever it resides.',
        fine: 'Loss of contract eligibility',
        severity: 'high',
        dlp_controls: ['data_classification', 'encryption_transit', 'access_controls'],
      },
    ],
  },

  {
    code: 'sox',
    short_name: 'SOX',
    name: 'Sarbanes-Oxley Act',
    regions: ['US'],
    industries: ['financial'],
    jurisdiction: 'United States',
    authority: 'Securities and Exchange Commission (SEC) / PCAOB',
    type: 'sector',
    summary: 'US federal law requiring publicly traded companies to implement internal controls over financial reporting and maintain accurate financial records. SOX Section 404 mandates management assessment of internal controls.',
    max_fine: 'Up to $5M and 20 years imprisonment for wilful violations; up to $1M and 10 years for individual violations',
    effective_date: '2002-07-30',
    requirements: [
      {
        article: 'Section 404',
        title: 'Management Assessment of Internal Controls',
        description: 'Management must annually assess the effectiveness of internal controls over financial reporting (ICFR) and external auditors must attest to the assessment.',
        dlp_relevance: 'DLP controls over financial data (access logs, data movement records) are key evidence for SOX Section 404 internal control assessments.',
        fine: '$1M–$5M and up to 20 years imprisonment',
        severity: 'critical',
        dlp_controls: ['data_classification', 'audit_logging', 'access_controls'],
      },
      {
        article: 'Section 802',
        title: 'Records Management and Retention',
        description: 'Prohibits alteration, destruction, or falsification of financial records. Requires retention of audit work papers and related records for 7 years.',
        dlp_relevance: 'DLP controls prevent unauthorised deletion or modification of financial records and ensure audit trails are preserved.',
        fine: '$1M–$5M and up to 20 years imprisonment',
        severity: 'critical',
        dlp_controls: ['audit_logging', 'access_controls', 'breach_detection'],
      },
      {
        article: 'Section 302',
        title: 'Corporate Responsibility for Financial Reports',
        description: 'CEOs and CFOs must personally certify the accuracy of financial statements and the effectiveness of internal controls.',
        dlp_relevance: 'DLP audit trails provide the evidence that executives rely on when certifying the integrity of financial data and internal controls.',
        fine: '$1M–$5M and up to 20 years imprisonment',
        severity: 'high',
        dlp_controls: ['audit_logging', 'data_classification'],
      },
    ],
  },

  // ── Global ───────────────────────────────────────────────────────────────────
  {
    code: 'pci_dss',
    short_name: 'PCI-DSS v4.0',
    name: 'Payment Card Industry Data Security Standard v4.0',
    regions: ['EU', 'EEA', 'UK', 'US', 'India', 'Singapore', 'Australia', 'Canada', 'Brazil', 'South Africa', 'Saudi Arabia', 'UAE', 'Japan', 'South Korea', 'China', 'Global'],
    industries: null,
    jurisdiction: 'Global',
    authority: 'PCI Security Standards Council',
    type: 'security',
    summary: 'Global security standard for all organisations that handle branded credit cards from major card schemes. PCI-DSS v4.0 strengthens requirements around targeted risk analysis and customised implementation.',
    max_fine: '$5,000–$100,000 per month per merchant/provider; card scheme penalties and potential card acceptance revocation',
    effective_date: '2024-03-31',
    requirements: [
      {
        article: 'Requirement 3',
        title: 'Protect Stored Account Data',
        description: 'Cardholder data and sensitive authentication data must be identified, classified, and protected wherever stored. Primary Account Numbers (PAN) must be rendered unreadable.',
        dlp_relevance: 'DLP identifies and prevents storage of unprotected cardholder data, enforcing PCI-DSS Requirement 3 across all data stores and channels.',
        fine: '$5,000–$100,000 per month',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_endpoint', 'dlp_saas'],
      },
      {
        article: 'Requirement 4',
        title: 'Protect Cardholder Data in Transit',
        description: 'Strong cryptography must be used to protect cardholder data during transmission over open, public networks.',
        dlp_relevance: 'DLP enforces encryption-in-transit policies and blocks unencrypted cardholder data from being transmitted via email, web uploads, or other channels.',
        fine: '$5,000–$100,000 per month',
        severity: 'critical',
        dlp_controls: ['encryption_transit', 'dlp_email', 'dlp_web'],
      },
      {
        article: 'Requirement 7',
        title: 'Restrict Access to System Components',
        description: 'Access to system components and cardholder data must be restricted to only those individuals whose job requires such access.',
        dlp_relevance: 'DLP access controls enforce need-to-know for cardholder data and prevent unauthorised users from accessing or exporting PCI data.',
        fine: '$5,000–$100,000 per month',
        severity: 'critical',
        dlp_controls: ['access_controls', 'data_classification'],
      },
      {
        article: 'Requirement 10',
        title: 'Log and Monitor All Access',
        description: 'All access to system components and cardholder data must be logged, and log data must be reviewed to identify anomalies or suspicious activity.',
        dlp_relevance: 'DLP audit logging provides the comprehensive activity logs required by PCI-DSS Requirement 10, including all access and transmission of cardholder data.',
        fine: '$5,000–$100,000 per month',
        severity: 'critical',
        dlp_controls: ['audit_logging', 'breach_detection'],
      },
    ],
  },

  // ── Asia-Pacific ─────────────────────────────────────────────────────────────
  {
    code: 'pdpa_sg',
    short_name: 'PDPA (SG)',
    name: 'Personal Data Protection Act (Singapore)',
    regions: ['Singapore'],
    industries: null,
    jurisdiction: 'Singapore',
    authority: 'Personal Data Protection Commission (PDPC)',
    type: 'privacy',
    summary: 'Singapore\'s comprehensive data protection law governing the collection, use, and disclosure of personal data by organisations. Includes mandatory breach notification and financial penalties.',
    max_fine: 'SGD 1M or 10% of annual turnover in Singapore (whichever is higher)',
    effective_date: '2014-07-02',
    requirements: [
      {
        article: 'Section 24 (Protection Obligation)',
        title: 'Protection of Personal Data',
        description: 'Organisations must protect personal data in their possession or control by making reasonable security arrangements to prevent unauthorised access, collection, use, disclosure, copying, modification, disposal, or similar risks.',
        dlp_relevance: 'DLP implements the PDPA\'s reasonable security arrangements requirement by preventing unauthorised access and disclosure across all channels.',
        fine: 'SGD 1M or 10% of annual turnover',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit'],
      },
      {
        article: 'Section 26D (Breach Notification)',
        title: 'Mandatory Data Breach Notification',
        description: 'Organisations must notify the PDPC within 3 calendar days and affected individuals without undue delay when a breach is likely to result in significant harm.',
        dlp_relevance: 'DLP breach detection enables organisations to identify and scope data breaches quickly, meeting the PDPC\'s strict 3-day notification window.',
        fine: 'SGD 1M or 10% of annual turnover',
        severity: 'critical',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
      {
        article: 'Section 25 (Retention Limitation)',
        title: 'Retention and Disposal',
        description: 'Personal data must not be retained longer than necessary and must be properly disposed of or anonymised when no longer needed.',
        dlp_relevance: 'DLP classification policies support data lifecycle management by identifying and controlling personal data throughout its lifecycle.',
        fine: 'SGD 1M or 10% of annual turnover',
        severity: 'medium',
        dlp_controls: ['data_classification'],
      },
    ],
  },

  {
    code: 'pipl',
    short_name: 'PIPL',
    name: 'Personal Information Protection Law',
    regions: ['China'],
    industries: null,
    jurisdiction: "People's Republic of China",
    authority: 'Cyberspace Administration of China (CAC)',
    type: 'privacy',
    summary: "China's comprehensive personal information protection law. Applies to organisations processing personal information of individuals in China, including cross-border data transfers (which require specific approval mechanisms).",
    max_fine: '¥50M (~€6.5M) or 5% of annual revenue; responsible persons face fines up to ¥1M',
    effective_date: '2021-11-01',
    requirements: [
      {
        article: 'Article 51',
        title: 'Personal Information Security Measures',
        description: 'Personal information processors must adopt necessary measures to safeguard personal information security, prevent unauthorised access, disclosure, alteration, and deletion.',
        dlp_relevance: 'DLP controls across web, email, endpoint, and SaaS channels are the primary technical measures for PIPL Article 51 compliance.',
        fine: '¥50M or 5% of annual revenue',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'access_controls'],
      },
      {
        article: 'Article 57',
        title: 'Personal Information Breach Notification',
        description: 'Processors must immediately notify the relevant authorities and affected individuals upon discovering a personal information breach.',
        dlp_relevance: 'DLP breach detection enables prompt identification of data breaches, supporting PIPL\'s immediate notification requirement.',
        fine: '¥50M or 5% of annual revenue',
        severity: 'critical',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
      {
        article: 'Article 38',
        title: 'Cross-Border Data Transfer Restrictions',
        description: 'Cross-border transfer of personal information requires CAC security assessment, approved standard contracts, or certification by a professional institution.',
        dlp_relevance: 'DLP controls on web uploads, email, and SaaS applications are essential for enforcing PIPL\'s strict cross-border transfer restrictions.',
        fine: '¥50M or 5% of annual revenue',
        severity: 'critical',
        dlp_controls: ['dlp_web', 'dlp_email', 'dlp_saas', 'data_classification'],
      },
    ],
  },

  {
    code: 'appi',
    short_name: 'APPI',
    name: 'Act on the Protection of Personal Information',
    regions: ['Japan'],
    industries: null,
    jurisdiction: 'Japan',
    authority: 'Personal Information Protection Commission (PPC)',
    type: 'privacy',
    summary: "Japan's primary data protection law, significantly amended in 2022 to strengthen individual rights, mandatory breach reporting, and controls over cross-border data transfers.",
    max_fine: '¥100M for corporations; ¥1M for individuals',
    effective_date: '2022-04-01',
    requirements: [
      {
        article: 'Article 23 / 24',
        title: 'Security Management Measures',
        description: 'Business operators handling personal information must take necessary and appropriate measures for the secure management of personal information to prevent leakage, loss, or damage.',
        dlp_relevance: 'DLP provides the technical security measures required under APPI for protecting personal information from leakage across all channels.',
        fine: '¥100M corporate fine',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit'],
      },
      {
        article: 'Article 26',
        title: 'Mandatory Breach Reporting',
        description: 'Businesses must report to the PPC and notify affected individuals when a breach involving personal information is likely to harm individuals\' rights and interests.',
        dlp_relevance: 'DLP breach detection enables timely identification of data breaches for APPI reporting obligations.',
        fine: '¥100M corporate fine',
        severity: 'high',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
    ],
  },

  {
    code: 'privacy_act_au',
    short_name: 'Privacy Act (AU)',
    name: 'Privacy Act 1988 (Australia)',
    regions: ['Australia'],
    industries: null,
    jurisdiction: 'Australia',
    authority: 'Office of the Australian Information Commissioner (OAIC)',
    type: 'privacy',
    summary: "Australia's primary privacy legislation, including the Australian Privacy Principles (APPs) and the Notifiable Data Breaches (NDB) scheme. The 2023 Review proposed significant strengthening of the law.",
    max_fine: 'AUD 50M, or 30% of adjusted turnover during breach period, or 3x benefit obtained (whichever is greater)',
    effective_date: '1988-12-21',
    requirements: [
      {
        article: 'APP 11',
        title: 'Security of Personal Information',
        description: 'Organisations must take reasonable steps to protect personal information from misuse, interference, and loss; and from unauthorised access, modification, or disclosure.',
        dlp_relevance: 'DLP implements APP 11\'s reasonable steps requirement by controlling access to and transmission of personal information across all channels.',
        fine: 'AUD 50M or 30% of adjusted turnover',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit', 'access_controls'],
      },
      {
        article: 'NDB Scheme (s26WH)',
        title: 'Notifiable Data Breach Reporting',
        description: 'Eligible data breaches must be reported to the OAIC and affected individuals as soon as practicable after the organisation becomes aware of the breach.',
        dlp_relevance: 'DLP breach detection is the triggering mechanism for the NDB scheme — it identifies eligible data breaches and provides the scope information needed for notification.',
        fine: 'AUD 50M or 30% of adjusted turnover',
        severity: 'critical',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
    ],
  },

  {
    code: 'pipa_kr',
    short_name: 'PIPA (KR)',
    name: 'Personal Information Protection Act (South Korea)',
    regions: ['South Korea'],
    industries: null,
    jurisdiction: 'South Korea',
    authority: 'Personal Information Protection Commission (PIPC)',
    type: 'privacy',
    summary: "South Korea's comprehensive data protection law, one of the strictest in Asia. Requires data localisation for certain sectors, mandatory DPO appointment, and strict security measures.",
    max_fine: '3% of annual revenue related to the violation; criminal fines up to KRW 100M',
    effective_date: '2011-09-30',
    requirements: [
      {
        article: 'Article 29',
        title: 'Safety Measures for Personal Information',
        description: 'Personal information controllers must implement technical, managerial, and physical measures to ensure the safety of personal information to prevent loss, theft, leakage, alteration, or damage.',
        dlp_relevance: 'DLP technical measures directly satisfy PIPA\'s safety measure requirements for preventing personal information leakage.',
        fine: '3% of annual revenue',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit'],
      },
      {
        article: 'Article 34',
        title: 'Notification of Data Breach',
        description: 'Controllers must notify affected data subjects and report to the PIPC without undue delay in the event of a data breach.',
        dlp_relevance: 'DLP breach detection enables prompt identification and scoping of data breaches for PIPA notification requirements.',
        fine: 'KRW 100M criminal fine',
        severity: 'high',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
    ],
  },

  // ── Middle East & Africa ─────────────────────────────────────────────────────
  {
    code: 'pdpl_sa',
    short_name: 'PDPL (SA)',
    name: 'Personal Data Protection Law (Saudi Arabia)',
    regions: ['Saudi Arabia'],
    industries: null,
    jurisdiction: 'Kingdom of Saudi Arabia',
    authority: 'National Data Management Office (NDMO)',
    type: 'privacy',
    summary: 'Saudi Arabia\'s comprehensive data protection law governing the processing of personal data of individuals in Saudi Arabia. Includes cross-border transfer restrictions and mandatory breach notification.',
    max_fine: 'SAR 5M (~€1.3M); SAR 3M for first violation',
    effective_date: '2023-09-14',
    requirements: [
      {
        article: 'Article 19',
        title: 'Security and Confidentiality',
        description: 'Controllers must implement adequate technical and organisational measures to protect personal data from breach, damage, unauthorised access, and illegal use.',
        dlp_relevance: 'DLP technical measures directly implement the security and confidentiality obligation under PDPL for personal data protection.',
        fine: 'SAR 5M per violation',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit', 'access_controls'],
      },
      {
        article: 'Article 28',
        title: 'Data Breach Notification',
        description: 'Controllers must notify the NDMO within 72 hours and affected data subjects without undue delay in the event of a personal data breach.',
        dlp_relevance: 'DLP breach detection provides the detection capability needed to identify breaches and meet the PDPL\'s 72-hour notification requirement.',
        fine: 'SAR 5M per violation',
        severity: 'critical',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
      {
        article: 'Article 29',
        title: 'Cross-Border Data Transfer',
        description: 'Transfer of personal data outside Saudi Arabia requires a legitimate basis and must not harm national interests, security, or the interests of data subjects.',
        dlp_relevance: 'DLP controls on web uploads, email, and cloud applications are essential for monitoring and controlling cross-border data transfers under PDPL.',
        fine: 'SAR 5M per violation',
        severity: 'high',
        dlp_controls: ['dlp_web', 'dlp_email', 'dlp_saas', 'data_classification'],
      },
    ],
  },

  {
    code: 'popia',
    short_name: 'POPIA',
    name: 'Protection of Personal Information Act',
    regions: ['South Africa'],
    industries: null,
    jurisdiction: 'South Africa',
    authority: 'Information Regulator (South Africa)',
    type: 'privacy',
    summary: 'South Africa\'s data protection law establishing conditions for the lawful processing of personal information. Applies to all responsible parties processing personal information of South African data subjects.',
    max_fine: 'ZAR 10M (~€500K); imprisonment up to 10 years for certain offences',
    effective_date: '2021-07-01',
    requirements: [
      {
        article: 'Section 19',
        title: 'Security Measures',
        description: 'Responsible parties must secure the integrity and confidentiality of personal information in their possession or under their control by taking appropriate, reasonable technical and organisational measures.',
        dlp_relevance: 'DLP technical measures implement the POPIA security obligation for protecting personal information across all channels.',
        fine: 'ZAR 10M per violation',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit', 'access_controls'],
      },
      {
        article: 'Section 22',
        title: 'Notification of Security Compromises',
        description: 'Where there are reasonable grounds to believe that the personal information of a data subject has been accessed or acquired by an unauthorised person, the responsible party must notify the Regulator and the data subject.',
        dlp_relevance: 'DLP breach detection enables identification of security compromises for POPIA notification obligations.',
        fine: 'ZAR 10M per violation',
        severity: 'high',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
    ],
  },

  // ── Americas ─────────────────────────────────────────────────────────────────
  {
    code: 'pipeda',
    short_name: 'PIPEDA',
    name: 'Personal Information Protection and Electronic Documents Act',
    regions: ['Canada'],
    industries: null,
    jurisdiction: 'Canada',
    authority: 'Office of the Privacy Commissioner of Canada (OPC)',
    type: 'privacy',
    summary: 'Canada\'s federal private sector data protection law. Mandatory Breach Reporting Regulations require notification to the OPC and affected individuals for breaches posing a real risk of significant harm. Bill C-27 (Consumer Privacy Protection Act) proposes significant updates.',
    max_fine: 'CAD 25M or 5% of global annual gross revenue (under proposed Bill C-27); current PIPEDA fine CAD 100,000',
    effective_date: '2000-04-13',
    requirements: [
      {
        article: 'Principle 7 (Schedule 1)',
        title: 'Safeguards',
        description: 'Personal information must be protected by security safeguards appropriate to the sensitivity of the information, including protection against loss or theft, and unauthorised access, disclosure, copying, use or modification.',
        dlp_relevance: 'DLP implements PIPEDA\'s safeguards principle, particularly for protecting sensitive personal information from unauthorised access and disclosure.',
        fine: 'CAD 100,000 (current); CAD 25M under Bill C-27',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit'],
      },
      {
        article: 'Breach Regulations §3',
        title: 'Mandatory Breach Reporting',
        description: 'Organisations must report breaches posing a real risk of significant harm to the Privacy Commissioner and notify affected individuals as soon as feasible.',
        dlp_relevance: 'DLP breach detection enables identification of breaches posing real risk of significant harm for PIPEDA reporting obligations.',
        fine: 'CAD 100,000 per violation',
        severity: 'high',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
    ],
  },

  {
    code: 'lgpd',
    short_name: 'LGPD',
    name: 'Lei Geral de Proteção de Dados Pessoais',
    regions: ['Brazil'],
    industries: null,
    jurisdiction: 'Brazil',
    authority: 'National Data Protection Authority (ANPD)',
    type: 'privacy',
    summary: "Brazil's comprehensive data protection law modelled on the GDPR. Applies to any processing of personal data of individuals in Brazil, regardless of where the processor is located.",
    max_fine: '2% of revenue in Brazil per violation, up to BRL 50M (~€9M) per violation',
    effective_date: '2020-09-18',
    requirements: [
      {
        article: 'Article 46',
        title: 'Security Measures',
        description: 'Controllers and processors must adopt security, technical, and administrative measures capable of protecting personal data from unauthorised access and accidental or unlawful situations of destruction, loss, alteration, communication, or any form of improper or unlawful treatment.',
        dlp_relevance: 'DLP is a primary technical measure under LGPD for protecting personal data from unauthorised access and exfiltration.',
        fine: '2% of Brazil revenue, max BRL 50M',
        severity: 'critical',
        dlp_controls: ['data_classification', 'dlp_web', 'dlp_email', 'dlp_endpoint', 'encryption_transit', 'access_controls'],
      },
      {
        article: 'Article 48',
        title: 'Incident Notification',
        description: 'Controllers must notify the ANPD and affected data subjects of security incidents that may create risk or relevant harm within a reasonable timeframe (typically 2 business days under ANPD guidance).',
        dlp_relevance: 'DLP breach detection enables identification of security incidents for LGPD notification obligations.',
        fine: '2% of Brazil revenue, max BRL 50M',
        severity: 'high',
        dlp_controls: ['breach_detection', 'audit_logging'],
      },
    ],
  },
]
