-- ── Compliance Tables ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS compliance_regulations (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code             text UNIQUE NOT NULL,
  short_name       text NOT NULL,
  name             text NOT NULL,
  regions          text[] NOT NULL,
  industries       text[],            -- NULL = all industries
  jurisdiction     text NOT NULL,
  authority        text,
  type             text NOT NULL,     -- 'privacy' | 'security' | 'sector'
  summary          text NOT NULL,
  max_fine         text,
  effective_date   date,
  last_verified_at timestamptz DEFAULT now(),
  active           boolean DEFAULT true,
  created_at       timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS compliance_requirements (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  regulation_id uuid NOT NULL REFERENCES compliance_regulations(id) ON DELETE CASCADE,
  article       text NOT NULL,
  title         text NOT NULL,
  description   text NOT NULL,
  dlp_relevance text NOT NULL,
  fine          text,
  severity      text NOT NULL,        -- 'critical' | 'high' | 'medium'
  dlp_controls  text[],
  created_at    timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS compliance_verification_log (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  regulation_id uuid NOT NULL REFERENCES compliance_regulations(id),
  org_id        uuid NOT NULL,
  verified_by   uuid,
  verified_at   timestamptz DEFAULT now(),
  changed       boolean DEFAULT false,
  changes       jsonb,
  notes         text
);

CREATE TABLE IF NOT EXISTS compliance_assessments (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id        uuid NOT NULL,
  control_key   text NOT NULL,
  regulation_id uuid NOT NULL REFERENCES compliance_regulations(id),
  status        text NOT NULL DEFAULT 'not_assessed',
  notes         text,
  updated_at    timestamptz DEFAULT now(),
  UNIQUE(org_id, control_key, regulation_id)
);

-- ── RLS ──────────────────────────────────────────────────────────────────────

ALTER TABLE compliance_regulations      ENABLE ROW LEVEL SECURITY;
ALTER TABLE compliance_requirements     ENABLE ROW LEVEL SECURITY;
ALTER TABLE compliance_verification_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE compliance_assessments      ENABLE ROW LEVEL SECURITY;

-- Regulations & requirements: public read (no org isolation needed — shared reference data)
CREATE POLICY "public_read" ON compliance_regulations
  FOR SELECT USING (true);

CREATE POLICY "public_read" ON compliance_requirements
  FOR SELECT USING (true);

-- Verification log & assessments: org-scoped
CREATE POLICY "org_isolation" ON compliance_verification_log
  USING (org_id = (auth.jwt() ->> 'org_id')::uuid);

CREATE POLICY "org_isolation" ON compliance_assessments
  USING (org_id = (auth.jwt() ->> 'org_id')::uuid);

-- ── Seed: Regulations ────────────────────────────────────────────────────────

INSERT INTO compliance_regulations (code, short_name, name, regions, industries, jurisdiction, authority, type, summary, max_fine, effective_date) VALUES
('gdpr',           'GDPR',          'General Data Protection Regulation',                    ARRAY['EU','EEA'],          NULL,                                          'European Union',          'Data Protection Authorities (per member state)',                   'privacy',  'The EU''s primary data protection law governing the collection, processing, and transfer of personal data of EU/EEA residents. Applies globally to any organisation handling EU/EEA personal data.',            '€20M or 4% of global annual turnover (whichever is higher)',                                              '2018-05-25'),
('uk_gdpr',        'UK GDPR',       'UK General Data Protection Regulation',                 ARRAY['UK'],                NULL,                                          'United Kingdom',          'Information Commissioner''s Office (ICO)',                          'privacy',  'The UK''s post-Brexit data protection law. Applies to organisations processing personal data of UK residents.',                                                                                                 '£17.5M or 4% of global annual turnover (whichever is higher)',                                            '2021-01-01'),
('nis2',           'NIS2',          'Network and Information Security Directive 2',           ARRAY['EU'],                ARRAY['critical_infrastructure','energy','transport','financial','healthcare','digital_infrastructure'], 'European Union', 'National Competent Authorities (per member state)', 'security', 'EU directive requiring essential and important entities to implement cybersecurity risk management measures and report significant incidents.',                                                                  '€10M or 2% of global annual turnover (essential); €7M or 1.4% (important)',                               '2024-10-17'),
('dora',           'DORA',          'Digital Operational Resilience Act',                    ARRAY['EU'],                ARRAY['financial'],                            'European Union',          'European Supervisory Authorities (EBA, EIOPA, ESMA)',               'sector',   'EU regulation requiring financial entities to manage ICT risks, test resilience, report ICT incidents, and manage third-party ICT risks.',                                                                       'Up to 1% of average daily worldwide turnover per day for up to 6 months',                                 '2025-01-17'),
('dpdp',           'DPDP Act',      'Digital Personal Data Protection Act 2023',             ARRAY['India'],             NULL,                                          'India',                   'Data Protection Board of India',                                   'privacy',  'India''s primary data protection legislation governing the processing of digital personal data of individuals in India.',                                                                                        '₹250 Crore (~€27M) per violation',                                                                        '2023-08-11'),
('rbi_csf',        'RBI CSF',       'RBI Cybersecurity Framework for Banks',                 ARRAY['India'],             ARRAY['financial'],                            'India',                   'Reserve Bank of India (RBI)',                                       'sector',   'Framework requiring scheduled commercial banks in India to implement a robust cybersecurity policy, incident response, and controls for protecting customer data.',                                              'Regulatory sanctions, penalties, and licence conditions',                                                  '2016-06-02'),
('sebi_cscrf',     'SEBI CSCRF',    'SEBI Cyber Security and Cyber Resilience Framework',   ARRAY['India'],             ARRAY['financial'],                            'India',                   'Securities and Exchange Board of India (SEBI)',                     'sector',   'Framework for SEBI-regulated entities covering cybersecurity governance, risk management, and incident response.',                                                                                               'Regulatory action including suspension or cancellation of registration',                                   '2023-08-25'),
('hipaa',          'HIPAA',         'Health Insurance Portability and Accountability Act',   ARRAY['US'],                ARRAY['healthcare'],                           'United States',           'U.S. Department of Health and Human Services (HHS) / OCR',         'sector',   'US federal law protecting individually identifiable health information (PHI) held by covered entities and business associates.',                                                                                  '$100 to $1.9M per violation category per year',                                                           '1996-08-21'),
('glba',           'GLBA',          'Gramm-Leach-Bliley Act (Safeguards Rule)',              ARRAY['US'],                ARRAY['financial'],                            'United States',           'Federal Trade Commission (FTC) / Federal Banking Regulators',       'sector',   'Requires US financial institutions to protect the security and confidentiality of customer financial information.',                                                                                              '$100,000 per violation for institutions; $10,000 per violation for individuals',                           '2003-05-23'),
('ccpa',           'CCPA/CPRA',     'California Consumer Privacy Act / California Privacy Rights Act', ARRAY['US'],     NULL,                                          'California, United States','California Privacy Protection Agency (CPPA)',                        'privacy',  'California''s comprehensive privacy law granting consumers rights over personal information. CPRA strengthened CCPA with a new enforcement agency.',                                                             '$2,500 per unintentional violation; $7,500 per intentional violation',                                    '2020-01-01'),
('cmmc',           'CMMC 2.0',      'Cybersecurity Maturity Model Certification 2.0',        ARRAY['US'],                ARRAY['defence','government'],                 'United States',           'U.S. Department of Defense (DoD)',                                  'security', 'DoD framework requiring defence contractors to achieve specific cybersecurity certification levels based on the sensitivity of data they handle.',                                                               'Loss of DoD contracts; False Claims Act penalties',                                                       '2021-11-04'),
('sox',            'SOX',           'Sarbanes-Oxley Act',                                    ARRAY['US'],                ARRAY['financial'],                            'United States',           'Securities and Exchange Commission (SEC) / PCAOB',                  'sector',   'US federal law requiring publicly traded companies to implement internal controls over financial reporting and maintain accurate financial records.',                                                              'Up to $5M and 20 years imprisonment for wilful violations',                                               '2002-07-30'),
('pci_dss',        'PCI-DSS v4.0',  'Payment Card Industry Data Security Standard v4.0',    ARRAY['EU','EEA','UK','US','India','Singapore','Australia','Canada','Brazil','South Africa','Saudi Arabia','UAE','Japan','South Korea','China','Global'], NULL, 'Global', 'PCI Security Standards Council', 'security', 'Global security standard for all organisations that handle branded credit cards from major card schemes.',                                                                                                       '$5,000–$100,000 per month per merchant/provider',                                                         '2024-03-31'),
('pdpa_sg',        'PDPA (SG)',      'Personal Data Protection Act (Singapore)',              ARRAY['Singapore'],         NULL,                                          'Singapore',               'Personal Data Protection Commission (PDPC)',                        'privacy',  'Singapore''s comprehensive data protection law governing the collection, use, and disclosure of personal data by organisations.',                                                                                 'SGD 1M or 10% of annual turnover in Singapore (whichever is higher)',                                     '2014-07-02'),
('pipl',           'PIPL',          'Personal Information Protection Law',                   ARRAY['China'],             NULL,                                          'People''s Republic of China','Cyberspace Administration of China (CAC)',                       'privacy',  'China''s comprehensive personal information protection law. Applies to organisations processing personal information of individuals in China.',                                                                  '¥50M (~€6.5M) or 5% of annual revenue',                                                                   '2021-11-01'),
('appi',           'APPI',          'Act on the Protection of Personal Information',         ARRAY['Japan'],             NULL,                                          'Japan',                   'Personal Information Protection Commission (PPC)',                  'privacy',  'Japan''s primary data protection law, amended in 2022 to strengthen individual rights, mandatory breach reporting, and cross-border transfer controls.',                                                          '¥100M for corporations; ¥1M for individuals',                                                             '2022-04-01'),
('privacy_act_au', 'Privacy Act (AU)', 'Privacy Act 1988 (Australia)',                      ARRAY['Australia'],         NULL,                                          'Australia',               'Office of the Australian Information Commissioner (OAIC)',          'privacy',  'Australia''s primary privacy legislation including the Australian Privacy Principles (APPs) and the Notifiable Data Breaches (NDB) scheme.',                                                                     'AUD 50M or 30% of adjusted turnover during breach period',                                                '1988-12-21'),
('pipa_kr',        'PIPA (KR)',      'Personal Information Protection Act (South Korea)',     ARRAY['South Korea'],       NULL,                                          'South Korea',             'Personal Information Protection Commission (PIPC)',                 'privacy',  'South Korea''s comprehensive data protection law. Requires data localisation for certain sectors, mandatory DPO appointment, and strict security measures.',                                                     '3% of annual revenue related to the violation',                                                           '2011-09-30'),
('pdpl_sa',        'PDPL (SA)',      'Personal Data Protection Law (Saudi Arabia)',           ARRAY['Saudi Arabia'],      NULL,                                          'Kingdom of Saudi Arabia', 'National Data Management Office (NDMO)',                            'privacy',  'Saudi Arabia''s data protection law governing the processing of personal data of individuals in Saudi Arabia, including cross-border transfer restrictions.',                                                    'SAR 5M (~€1.3M) per violation',                                                                           '2023-09-14'),
('popia',          'POPIA',         'Protection of Personal Information Act',                ARRAY['South Africa'],      NULL,                                          'South Africa',            'Information Regulator (South Africa)',                              'privacy',  'South Africa''s data protection law establishing conditions for the lawful processing of personal information.',                                                                                                 'ZAR 10M (~€500K); imprisonment up to 10 years for certain offences',                                     '2021-07-01'),
('pipeda',         'PIPEDA',        'Personal Information Protection and Electronic Documents Act', ARRAY['Canada'],     NULL,                                          'Canada',                  'Office of the Privacy Commissioner of Canada (OPC)',               'privacy',  'Canada''s federal private sector data protection law. Mandatory breach reporting for breaches posing a real risk of significant harm.',                                                                           'CAD 25M or 5% of global annual gross revenue (under proposed Bill C-27)',                                 '2000-04-13'),
('lgpd',           'LGPD',          'Lei Geral de Proteção de Dados Pessoais',               ARRAY['Brazil'],            NULL,                                          'Brazil',                  'National Data Protection Authority (ANPD)',                         'privacy',  'Brazil''s comprehensive data protection law modelled on GDPR. Applies to any processing of personal data of individuals in Brazil.',                                                                             '2% of revenue in Brazil per violation, up to BRL 50M (~€9M) per violation',                              '2020-09-18')
ON CONFLICT (code) DO NOTHING;

-- ── Seed: Requirements ───────────────────────────────────────────────────────

INSERT INTO compliance_requirements (regulation_id, article, title, description, dlp_relevance, fine, severity, dlp_controls)
SELECT r.id, req.article, req.title, req.description, req.dlp_relevance, req.fine, req.severity, req.dlp_controls
FROM compliance_regulations r
JOIN (VALUES
  -- GDPR
  ('gdpr','Article 5(1)(f)','Integrity and Confidentiality','Personal data must be processed securely to protect against unauthorised or unlawful processing and against accidental loss, destruction or damage.','DLP directly enforces this principle by preventing unauthorised data exfiltration across all channels (web, email, endpoint, SaaS).','€20M or 4% of global annual turnover','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','dlp_saas']),
  ('gdpr','Article 25','Data Protection by Design and by Default','Controllers must implement appropriate technical and organisational measures to integrate data protection principles into processing activities by design and by default.','DLP policies must be built into systems from the start — not bolted on. Data classification and access controls are the foundation of privacy-by-design.','€10M or 2% of global annual turnover','high',ARRAY['data_classification','access_controls','dlp_saas']),
  ('gdpr','Article 32','Security of Processing','Controllers and processors must implement appropriate technical and organisational measures including encryption, pseudonymisation, and ongoing confidentiality.','The core technical obligation. DLP tools are a primary mechanism for meeting Art. 32 — covering encryption in transit, access controls, and preventing unauthorised disclosure.','€10M or 2% of global annual turnover','critical',ARRAY['dlp_web','dlp_email','dlp_endpoint','dlp_saas','genai_controls','encryption_transit','access_controls']),
  ('gdpr','Article 33','Notification of Personal Data Breach (72-hour)','The controller must notify the relevant supervisory authority within 72 hours of becoming aware of a personal data breach.','DLP alerting and audit logging are the detection mechanism. Without them, organisations cannot identify breaches in time to meet the 72-hour notification window.','€10M or 2% of global annual turnover','critical',ARRAY['audit_logging','breach_detection']),
  ('gdpr','Article 34','Communication of Breach to Data Subject','When a breach is likely to result in high risk to individuals, the controller must communicate the breach without undue delay.','DLP breach detection identifies the scope of a breach (which data, which individuals), enabling accurate communication to affected data subjects.','€20M or 4% of global annual turnover','high',ARRAY['breach_detection','audit_logging']),

  -- UK GDPR
  ('uk_gdpr','Article 5(1)(f)','Integrity and Confidentiality','Personal data must be processed securely to protect against unauthorised processing and accidental loss or damage.','Same as EU GDPR — DLP enforces the integrity and confidentiality principle across all data channels.','£17.5M or 4% of global annual turnover','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','dlp_saas']),
  ('uk_gdpr','Article 32','Security of Processing','Appropriate technical and organisational measures must be implemented to ensure data security, including encryption and ongoing confidentiality.','DLP is a primary technical measure for meeting the security of processing obligation under UK GDPR.','£10M or 2% of global annual turnover','critical',ARRAY['dlp_web','dlp_email','encryption_transit','access_controls','genai_controls']),
  ('uk_gdpr','Article 33','Breach Notification (72-hour)','Notify the ICO within 72 hours of becoming aware of a personal data breach.','DLP audit logs provide the evidence trail needed to identify breach timing and scope for ICO notification.','£17.5M or 4% of global annual turnover','critical',ARRAY['audit_logging','breach_detection']),
  ('uk_gdpr','ICO Guidelines','Accountability and Governance','Organisations must demonstrate compliance and maintain records of processing activities.','DLP audit trails and classification policies are key evidence of accountability to the ICO.','£8.75M or 2% of global annual turnover','high',ARRAY['data_classification','audit_logging']),

  -- NIS2
  ('nis2','Article 21(2)(a)','Risk Analysis and Security Policies','Risk analysis and information system security policies covering all aspects of cybersecurity risk management.','DLP gap assessments feed directly into the risk analysis required under NIS2 for data exfiltration risks.','€10M or 2% of global annual turnover','high',ARRAY['data_classification','audit_logging']),
  ('nis2','Article 21(2)(b)','Incident Handling','Entities must have policies and procedures for handling cybersecurity incidents, including detection, containment, and recovery.','DLP breach detection and audit logging are core to incident detection and response capabilities required by NIS2.','€10M or 2% of global annual turnover','critical',ARRAY['breach_detection','audit_logging']),
  ('nis2','Article 21(2)(d)','Supply Chain Security','Security in supply chain relationships, including security aspects concerning relationships with direct suppliers or service providers.','DLP controls on SaaS applications and data sharing with third parties directly address supply chain data security.','€10M or 2% of global annual turnover','high',ARRAY['dlp_saas','data_classification','access_controls']),
  ('nis2','Article 21(2)(h)','Access Control and Human Resources Security','Access control policies including need-to-know, multi-factor authentication, and human resources security measures.','DLP access controls and data classification enforce need-to-know principles across all data channels.','€10M or 2% of global annual turnover','high',ARRAY['access_controls','data_classification','dlp_endpoint']),

  -- DORA
  ('dora','Article 8','ICT Asset Management','Financial entities must identify, classify and document all ICT assets, including those that support critical or important functions.','Data classification is fundamental to ICT asset management — knowing what data exists and where it flows.','Supervisory measures','high',ARRAY['data_classification']),
  ('dora','Article 9','Protection and Prevention','Financial entities must put in place ICT security policies to ensure the protection of ICT assets from cyberattacks.','DLP tools are a primary protection measure for preventing data exfiltration and insider threats within financial entities.','Supervisory measures and periodic penalty payments','critical',ARRAY['dlp_web','dlp_email','dlp_endpoint','dlp_saas','access_controls']),
  ('dora','Article 10','Detection','Financial entities must have mechanisms for promptly detecting anomalous activities including ICT-related incidents.','DLP anomaly detection and audit logging are core detection mechanisms for data-related ICT incidents.','Supervisory measures','high',ARRAY['audit_logging','breach_detection']),
  ('dora','Article 17','ICT-Related Incident Management','Financial entities must establish and implement ICT-related incident management processes for detecting, managing, and notifying incidents.','DLP breach detection and audit logging are the first line of incident detection for data-related breaches.','Supervisory measures','critical',ARRAY['breach_detection','audit_logging']),

  -- DPDP Act
  ('dpdp','Section 8(4)','Security Safeguards','Data fiduciaries must implement appropriate technical and organisational measures to protect personal data.','DLP is a core technical safeguard under DPDP — preventing unauthorised access and exfiltration of personal data.','₹250 Crore per violation','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit','access_controls']),
  ('dpdp','Section 8(6)','Personal Data Breach Notification','Data fiduciaries must notify the Data Protection Board and affected data principals in the event of a personal data breach.','DLP breach detection and audit logging enable organisations to identify breaches quickly for Board notification.','₹200 Crore per violation','critical',ARRAY['breach_detection','audit_logging']),
  ('dpdp','Section 6','Purpose Limitation and Data Minimisation','Personal data must be processed only for the specific lawful purpose and not retained beyond the necessary period.','DLP classification policies enforce purpose limitation by controlling where and how different categories of personal data can flow.','₹150 Crore per violation','high',ARRAY['data_classification','access_controls','dlp_saas']),
  ('dpdp','Section 9','Processing of Children''s Personal Data','Data fiduciaries must obtain verifiable parental consent before processing personal data of children (under 18).','DLP content inspection can detect and block the unauthorised processing or transfer of data tagged as belonging to minors.','₹200 Crore per violation','high',ARRAY['data_classification','dlp_web','dlp_saas']),

  -- RBI CSF
  ('rbi_csf','Annex I — Controls','Data-at-Rest and Data-in-Transit Protection','Banks must implement encryption and access controls for sensitive customer data both at rest and in transit.','DLP enforces encryption-in-transit policies and prevents unencrypted sensitive banking data from leaving the organisation.','Regulatory penalty under BR Act','critical',ARRAY['encryption_transit','dlp_email','dlp_web','access_controls']),
  ('rbi_csf','Section 6 — Incident Response','Cyber Incident Reporting (6-hour rule)','Banks must report cybersecurity incidents to RBI within 2–6 hours of detection.','DLP alerting provides immediate notification of data exfiltration events, enabling banks to meet the RBI''s strict 6-hour reporting window.','Regulatory penalty under BR Act','critical',ARRAY['breach_detection','audit_logging']),
  ('rbi_csf','Section 4 — Data Classification','Data Classification and Handling','Banks must classify data based on sensitivity and implement controls commensurate with the classification level.','Data classification is the foundation of the RBI framework — all other DLP controls flow from proper classification.','Regulatory penalty','high',ARRAY['data_classification','dlp_endpoint']),

  -- SEBI CSCRF
  ('sebi_cscrf','Section 3 — Controls','Data Leakage Prevention','SEBI-regulated entities must implement DLP solutions to prevent unauthorised disclosure of confidential securities market data.','SEBI explicitly requires DLP implementation as a mandatory control for protecting market-sensitive information.','Regulatory sanctions','critical',ARRAY['dlp_web','dlp_email','dlp_endpoint','dlp_saas','data_classification']),
  ('sebi_cscrf','Section 4 — Incident Management','Incident Detection and Reporting','Entities must implement mechanisms to detect, respond to, and report cybersecurity incidents to SEBI.','DLP audit logging and breach detection provide the detection layer required for SEBI incident management.','Regulatory sanctions','high',ARRAY['audit_logging','breach_detection']),
  ('sebi_cscrf','Section 2 — Governance','Data Classification and Access Control','Regulated entities must classify data based on sensitivity, implement access controls, and maintain audit trails.','Data classification and access controls are foundational to the SEBI framework — particularly for preventing insider trading data leaks.','Regulatory sanctions','high',ARRAY['data_classification','access_controls','audit_logging']),

  -- HIPAA
  ('hipaa','§164.308(a)(1)','Security Management Process','Covered entities must implement policies and procedures to prevent, detect, contain, and correct security violations, including risk analysis.','DLP is a core risk management control under HIPAA — it prevents unauthorised disclosure of PHI and provides evidence for risk analysis.','$100,000 to $1.9M per violation category','critical',ARRAY['data_classification','breach_detection','audit_logging']),
  ('hipaa','§164.312(a)(1)','Access Control','Implement technical policies allowing ePHI access only to authorised persons or software programs.','DLP access controls enforce who can access, copy, or transmit ePHI, preventing both insider threats and accidental disclosure.','$100,000 to $1.9M per violation category','critical',ARRAY['access_controls','dlp_endpoint','dlp_saas']),
  ('hipaa','§164.312(b)','Audit Controls','Implement hardware, software, and/or procedural mechanisms that record and examine activity in systems containing ePHI.','DLP audit logging is a direct implementation of the HIPAA audit controls requirement, providing full activity trails for ePHI.','$100,000 to $1.9M per violation category','critical',ARRAY['audit_logging']),
  ('hipaa','§164.312(c)(1)','Integrity Controls','Implement policies and procedures to protect ePHI from improper alteration or destruction.','DLP prevents unauthorised modification or deletion of ePHI by controlling who can access and manipulate PHI files.','$100,000 to $1.9M per violation category','high',ARRAY['data_classification','access_controls','dlp_endpoint']),
  ('hipaa','§164.312(e)(1)','Transmission Security','Implement technical security measures to guard against unauthorised access to ePHI transmitted over networks.','DLP enforces encryption in transit and blocks unencrypted PHI from being transmitted via email, web, or other channels.','$100,000 to $1.9M per violation category','critical',ARRAY['encryption_transit','dlp_email','dlp_web']),

  -- GLBA
  ('glba','16 CFR §314.4(c)','Access Controls','Financial institutions must implement multi-factor authentication, access limitations, and encryption of customer data.','DLP enforces the access control and encryption requirements for customer financial data across all channels.','$100,000 per violation','critical',ARRAY['access_controls','encryption_transit','dlp_endpoint']),
  ('glba','16 CFR §314.4(d)','Encryption of Customer Information','Customer information in transit over external networks or at rest must be encrypted using current cryptographic standards.','DLP enforces encryption-in-transit policies and blocks unencrypted customer financial data from leaving the organisation.','$100,000 per violation','critical',ARRAY['encryption_transit','dlp_email','dlp_web']),
  ('glba','16 CFR §314.4(f)','Monitor and Test','Financial institutions must regularly monitor and test the effectiveness of security controls.','DLP testing (via Control Validator) and audit trail review are the monitoring mechanisms required under GLBA.','$100,000 per violation','high',ARRAY['audit_logging','breach_detection']),
  ('glba','16 CFR §314.4(h)','Incident Response Plan','Institutions must establish a written incident response plan to address unauthorised access to or use of customer information.','DLP breach detection is the triggering mechanism for the GLBA incident response plan.','$100,000 per violation','high',ARRAY['breach_detection','audit_logging']),

  -- CCPA/CPRA
  ('ccpa','§1798.81.5','Reasonable Security Measures','Businesses must implement and maintain reasonable security procedures and practices appropriate to the nature of the personal information they collect.','DLP is a cornerstone of "reasonable security" for businesses holding Californian consumer data — covering web, email, endpoint, and SaaS channels.','$100–$750 per consumer per incident','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit']),
  ('ccpa','§1798.150','Private Right of Action for Data Breaches','Consumers have a private right of action against businesses for data breaches resulting from failure to implement reasonable security measures.','DLP prevents the data breaches that trigger CCPA/CPRA private litigation — each blocked exfiltration is a prevented lawsuit.','$100–$750 per consumer per incident or actual damages','critical',ARRAY['breach_detection','audit_logging','dlp_web','dlp_email']),
  ('ccpa','CPRA §1798.100(d)','Data Minimisation and Purpose Limitation','Businesses must not collect more personal information than reasonably necessary and must not use it for incompatible purposes.','DLP classification policies enforce purpose limitation by controlling data flows and preventing use beyond disclosed purposes.','$2,500–$7,500 per violation','medium',ARRAY['data_classification','dlp_saas','access_controls']),

  -- CMMC
  ('cmmc','AC.L2-3.1.3','CUI Flow Control','Control the flow of Controlled Unclassified Information (CUI) in accordance with approved authorisations.','DLP directly implements CUI flow control — the primary control for preventing unauthorised CUI disclosure across all channels.','Loss of contract eligibility','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','dlp_saas']),
  ('cmmc','AU.L2-3.3.1','Audit Logging','Create and retain system audit logs and records to enable monitoring, analysis, investigation, and reporting of unlawful or unauthorised system activity.','DLP audit logging provides the required audit records for all CUI-related activities and potential incidents.','Loss of contract eligibility','critical',ARRAY['audit_logging']),
  ('cmmc','MP.L2-3.8.5','Media Sanitisation and Protection','Control access to media containing CUI and sanitise or destroy media before disposal or reuse.','DLP endpoint controls prevent CUI from being copied to removable media and enforce controls over physical data transfer.','Loss of contract eligibility','high',ARRAY['dlp_endpoint','access_controls']),
  ('cmmc','SC.L2-3.13.16','CUI at Rest','Protect the confidentiality of CUI at rest.','DLP classification and access controls ensure CUI is identified and protected wherever it resides.','Loss of contract eligibility','high',ARRAY['data_classification','encryption_transit','access_controls']),

  -- SOX
  ('sox','Section 404','Management Assessment of Internal Controls','Management must annually assess the effectiveness of internal controls over financial reporting (ICFR).','DLP controls over financial data (access logs, data movement records) are key evidence for SOX Section 404 internal control assessments.','$1M–$5M and up to 20 years imprisonment','critical',ARRAY['data_classification','audit_logging','access_controls']),
  ('sox','Section 802','Records Management and Retention','Prohibits alteration or destruction of financial records. Requires retention of audit work papers for 7 years.','DLP controls prevent unauthorised deletion or modification of financial records and ensure audit trails are preserved.','$1M–$5M and up to 20 years imprisonment','critical',ARRAY['audit_logging','access_controls','breach_detection']),
  ('sox','Section 302','Corporate Responsibility for Financial Reports','CEOs and CFOs must personally certify the accuracy of financial statements and the effectiveness of internal controls.','DLP audit trails provide the evidence executives rely on when certifying the integrity of financial data and internal controls.','$1M–$5M and up to 20 years imprisonment','high',ARRAY['audit_logging','data_classification']),

  -- PCI-DSS
  ('pci_dss','Requirement 3','Protect Stored Account Data','Cardholder data and sensitive authentication data must be identified, classified, and protected wherever stored.','DLP identifies and prevents storage of unprotected cardholder data, enforcing PCI-DSS Requirement 3 across all data stores.','$5,000–$100,000 per month','critical',ARRAY['data_classification','dlp_endpoint','dlp_saas']),
  ('pci_dss','Requirement 4','Protect Cardholder Data in Transit','Strong cryptography must be used to protect cardholder data during transmission over open, public networks.','DLP enforces encryption-in-transit policies and blocks unencrypted cardholder data from being transmitted via email, web, or other channels.','$5,000–$100,000 per month','critical',ARRAY['encryption_transit','dlp_email','dlp_web']),
  ('pci_dss','Requirement 7','Restrict Access to System Components','Access to system components and cardholder data must be restricted to only those individuals whose job requires such access.','DLP access controls enforce need-to-know for cardholder data and prevent unauthorised users from accessing or exporting PCI data.','$5,000–$100,000 per month','critical',ARRAY['access_controls','data_classification']),
  ('pci_dss','Requirement 10','Log and Monitor All Access','All access to system components and cardholder data must be logged and log data reviewed for anomalies or suspicious activity.','DLP audit logging provides the comprehensive activity logs required by PCI-DSS Requirement 10.','$5,000–$100,000 per month','critical',ARRAY['audit_logging','breach_detection']),

  -- PDPA (SG)
  ('pdpa_sg','Section 24 (Protection Obligation)','Protection of Personal Data','Organisations must protect personal data by making reasonable security arrangements to prevent unauthorised access, collection, use, or disclosure.','DLP implements the PDPA''s reasonable security arrangements requirement by preventing unauthorised access and disclosure across all channels.','SGD 1M or 10% of annual turnover','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit']),
  ('pdpa_sg','Section 26D (Breach Notification)','Mandatory Data Breach Notification (3-day)','Organisations must notify the PDPC within 3 calendar days for breaches likely to result in significant harm.','DLP breach detection enables organisations to identify and scope data breaches quickly, meeting the PDPC''s strict 3-day notification window.','SGD 1M or 10% of annual turnover','critical',ARRAY['breach_detection','audit_logging']),
  ('pdpa_sg','Section 25 (Retention Limitation)','Retention and Disposal','Personal data must not be retained longer than necessary and must be properly disposed of when no longer needed.','DLP classification policies support data lifecycle management by identifying and controlling personal data throughout its lifecycle.','SGD 1M or 10% of annual turnover','medium',ARRAY['data_classification']),

  -- PIPL
  ('pipl','Article 51','Personal Information Security Measures','Personal information processors must adopt necessary measures to safeguard personal information security, prevent unauthorised access, disclosure, alteration, and deletion.','DLP controls across web, email, endpoint, and SaaS channels are the primary technical measures for PIPL Article 51 compliance.','¥50M or 5% of annual revenue','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','access_controls']),
  ('pipl','Article 57','Personal Information Breach Notification','Processors must immediately notify the relevant authorities and affected individuals upon discovering a personal information breach.','DLP breach detection enables prompt identification of data breaches, supporting PIPL''s immediate notification requirement.','¥50M or 5% of annual revenue','critical',ARRAY['breach_detection','audit_logging']),
  ('pipl','Article 38','Cross-Border Data Transfer Restrictions','Cross-border transfer of personal information requires CAC security assessment, approved standard contracts, or certification.','DLP controls on web uploads, email, and SaaS applications are essential for enforcing PIPL''s strict cross-border transfer restrictions.','¥50M or 5% of annual revenue','critical',ARRAY['dlp_web','dlp_email','dlp_saas','data_classification']),

  -- APPI
  ('appi','Article 23 / 24','Security Management Measures','Business operators must take necessary and appropriate measures for the secure management of personal information to prevent leakage, loss, or damage.','DLP provides the technical security measures required under APPI for protecting personal information from leakage across all channels.','¥100M corporate fine','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit']),
  ('appi','Article 26','Mandatory Breach Reporting','Businesses must report to the PPC and notify affected individuals when a breach is likely to harm individuals'' rights and interests.','DLP breach detection enables timely identification of data breaches for APPI reporting obligations.','¥100M corporate fine','high',ARRAY['breach_detection','audit_logging']),

  -- Privacy Act AU
  ('privacy_act_au','APP 11','Security of Personal Information','Organisations must take reasonable steps to protect personal information from misuse, interference, loss, and unauthorised access, modification, or disclosure.','DLP implements APP 11''s reasonable steps requirement by controlling access to and transmission of personal information across all channels.','AUD 50M or 30% of adjusted turnover','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit','access_controls']),
  ('privacy_act_au','NDB Scheme (s26WH)','Notifiable Data Breach Reporting','Eligible data breaches must be reported to the OAIC and affected individuals as soon as practicable.','DLP breach detection is the triggering mechanism for the NDB scheme — it identifies eligible data breaches and provides scope information for notification.','AUD 50M or 30% of adjusted turnover','critical',ARRAY['breach_detection','audit_logging']),

  -- PIPA (KR)
  ('pipa_kr','Article 29','Safety Measures for Personal Information','Personal information controllers must implement technical, managerial, and physical measures to prevent loss, theft, leakage, alteration, or damage.','DLP technical measures directly satisfy PIPA''s safety measure requirements for preventing personal information leakage.','3% of annual revenue','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit']),
  ('pipa_kr','Article 34','Notification of Data Breach','Controllers must notify affected data subjects and report to the PIPC without undue delay in the event of a data breach.','DLP breach detection enables prompt identification and scoping of data breaches for PIPA notification requirements.','KRW 100M criminal fine','high',ARRAY['breach_detection','audit_logging']),

  -- PDPL (SA)
  ('pdpl_sa','Article 19','Security and Confidentiality','Controllers must implement adequate technical and organisational measures to protect personal data from breach, damage, unauthorised access, and illegal use.','DLP technical measures directly implement the security and confidentiality obligation under PDPL for personal data protection.','SAR 5M per violation','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit','access_controls']),
  ('pdpl_sa','Article 28','Data Breach Notification (72-hour)','Controllers must notify the NDMO within 72 hours and affected data subjects without undue delay in the event of a personal data breach.','DLP breach detection provides the capability needed to identify breaches and meet the PDPL''s 72-hour notification requirement.','SAR 5M per violation','critical',ARRAY['breach_detection','audit_logging']),
  ('pdpl_sa','Article 29','Cross-Border Data Transfer','Transfer of personal data outside Saudi Arabia requires a legitimate basis and must not harm national interests or the interests of data subjects.','DLP controls on web uploads, email, and cloud applications are essential for monitoring and controlling cross-border data transfers under PDPL.','SAR 5M per violation','high',ARRAY['dlp_web','dlp_email','dlp_saas','data_classification']),

  -- POPIA
  ('popia','Section 19','Security Measures','Responsible parties must secure the integrity and confidentiality of personal information by taking appropriate, reasonable technical and organisational measures.','DLP technical measures implement the POPIA security obligation for protecting personal information across all channels.','ZAR 10M per violation','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit','access_controls']),
  ('popia','Section 22','Notification of Security Compromises','Where there are reasonable grounds to believe personal information has been accessed by an unauthorised person, the responsible party must notify the Regulator and the data subject.','DLP breach detection enables identification of security compromises for POPIA notification obligations.','ZAR 10M per violation','high',ARRAY['breach_detection','audit_logging']),

  -- PIPEDA
  ('pipeda','Principle 7 (Schedule 1)','Safeguards','Personal information must be protected by security safeguards appropriate to the sensitivity of the information, including protection against unauthorised access, disclosure, copying, use or modification.','DLP implements PIPEDA''s safeguards principle, particularly for protecting sensitive personal information from unauthorised access and disclosure.','CAD 100,000 (current); CAD 25M under Bill C-27','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit']),
  ('pipeda','Breach Regulations §3','Mandatory Breach Reporting','Organisations must report breaches posing a real risk of significant harm to the Privacy Commissioner and notify affected individuals as soon as feasible.','DLP breach detection enables identification of breaches posing real risk of significant harm for PIPEDA reporting obligations.','CAD 100,000 per violation','high',ARRAY['breach_detection','audit_logging']),

  -- LGPD
  ('lgpd','Article 46','Security Measures','Controllers and processors must adopt security, technical, and administrative measures capable of protecting personal data from unauthorised access and accidental or unlawful situations of destruction, loss, alteration, communication, or any form of improper or unlawful treatment.','DLP is a primary technical measure under LGPD for protecting personal data from unauthorised access and exfiltration.','2% of Brazil revenue, max BRL 50M','critical',ARRAY['data_classification','dlp_web','dlp_email','dlp_endpoint','encryption_transit','access_controls']),
  ('lgpd','Article 48','Incident Notification','Controllers must notify the ANPD and affected data subjects of security incidents that may create risk or relevant harm (typically within 2 business days under ANPD guidance).','DLP breach detection enables identification of security incidents for LGPD notification obligations.','2% of Brazil revenue, max BRL 50M','high',ARRAY['breach_detection','audit_logging'])

) AS req(code, article, title, description, dlp_relevance, fine, severity, dlp_controls)
  ON r.code = req.code;
