-- ─────────────────────────────────────────────────────────────────────────────
-- 022_expand_catalog_examples.sql
-- Expand examples for all catalog_data_types to 6–10 specific entries each.
-- Uses UPDATE ... WHERE slug = '...' so it's safe to re-run on existing data.
-- ─────────────────────────────────────────────────────────────────────────────

-- ══ PUBLIC ════════════════════════════════════════════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Public web pages','Product pages','Landing pages','FAQ pages','Blog posts','Help center articles','About us pages','Release notes','Technical documentation'] WHERE slug = 'published-website-content';
UPDATE catalog_data_types SET examples = ARRAY['Brochures','Flyers','Display advertisements','Campaign one-pagers','Email marketing templates','Social media graphics','Trade show materials','Product sheets','Digital ad creatives'] WHERE slug = 'public-marketing-material';
UPDATE catalog_data_types SET examples = ARRAY['Approved press statements','Corporate announcements','Product launch press releases','Partnership announcements','Award announcements','Financial results press releases','Leadership appointment announcements'] WHERE slug = 'press-releases';
UPDATE catalog_data_types SET examples = ARRAY['Approved brand posts','Public campaign posts','Social media graphics','Scheduled tweets and LinkedIn posts','Community announcements','Public event promotion posts','Influencer partnership content'] WHERE slug = 'public-social-media-content';
UPDATE catalog_data_types SET examples = ARRAY['Public user guides','Release notes','Public knowledge base articles','Getting started guides','API reference docs','SDK documentation','Integration guides','Changelog entries','Troubleshooting articles'] WHERE slug = 'public-product-documentation';
UPDATE catalog_data_types SET examples = ARRAY['Published privacy policy','Cookie policy','Public terms of service','Accessibility statement','Acceptable use policy','Open source licence texts','Public GDPR disclosures'] WHERE slug = 'public-legal-documents';
UPDATE catalog_data_types SET examples = ARRAY['Published annual reports','Public investor presentations','Quarterly earnings releases','Public financial statements','Shareholder letters','Prospectus documents','ESG reports'] WHERE slug = 'public-investor-information';
UPDATE catalog_data_types SET examples = ARRAY['Job postings','Career page content','Public recruitment ads','Graduate programme pages','Internship listings','Employee value proposition content','Open day invitations'] WHERE slug = 'public-recruitment-content';
UPDATE catalog_data_types SET examples = ARRAY['Webinar pages','Public event invitations','Conference pages','Meetup listings','Public workshop announcements','Speaker session details','Event registration pages'] WHERE slug = 'public-event-information';
UPDATE catalog_data_types SET examples = ARRAY['Published blog posts','Public whitepapers','Approved case studies','Research reports for public release','Analyst briefing materials','Industry guides','Thought leadership articles'] WHERE slug = 'public-thought-leadership';
UPDATE catalog_data_types SET examples = ARRAY['Public troubleshooting guides','Public service status pages','Community forum posts','Known issues pages','Self-service support articles','Video tutorials','Chatbot knowledge base content'] WHERE slug = 'public-support-content';
UPDATE catalog_data_types SET examples = ARRAY['Public certification badges','Public compliance statements','ISO 27001 public certificates','SOC 2 summary reports','Public accreditation pages','Industry award listings'] WHERE slug = 'public-certifications';

-- ══ INTERNAL ══════════════════════════════════════════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Process guides','Workflow documentation','Operational procedures','Runbooks','Change management procedures','Escalation procedures','Approval workflows','Onboarding checklists','Incident response procedures','Standard operating procedures'] WHERE slug = 'internal-sop';
UPDATE catalog_data_types SET examples = ARRAY['Internal courses','Training guides','Onboarding material','E-learning modules','Compliance training decks','Skills assessment quizzes','Role-specific training packs','Manager toolkits','Soft skills workshops','Product training materials'] WHERE slug = 'internal-training';
UPDATE catalog_data_types SET examples = ARRAY['Meeting minutes','Action item lists','Team notes','All-hands meeting notes','Project kick-off notes','Committee meeting notes','1:1 notes without sensitive content','Sprint retrospective notes','Workshop output notes'] WHERE slug = 'internal-meeting-notes';
UPDATE catalog_data_types SET examples = ARRAY['Task boards','Sprint logs','Project status updates','Risk trackers without sensitive data','Resource allocation sheets','Milestone trackers','Project retrospective outputs','Dependency maps','RAID logs'] WHERE slug = 'internal-project-trackers';
UPDATE catalog_data_types SET examples = ARRAY['Internal IT support docs','App usage guides','Internal FAQs','Software installation guides','VPN setup instructions','Password reset procedures','Device setup guides','IT request forms','Shadow IT guidance'] WHERE slug = 'internal-it-guides';
UPDATE catalog_data_types SET examples = ARRAY['Internal emails','Team announcements','Routine business updates','All-staff newsletters','Internal blog posts','Intranet announcements','Town hall summaries','Departmental updates','Internal policy reminders'] WHERE slug = 'internal-communication';
UPDATE catalog_data_types SET examples = ARRAY['Internal wiki pages','How-to guides','Internal reference docs','Confluence pages','SharePoint internal pages','Playbooks','Process documentation','Glossaries','Onboarding wikis','Best practice guides'] WHERE slug = 'internal-knowledge-base';
UPDATE catalog_data_types SET examples = ARRAY['Non-sensitive asset lists','Equipment registers','Stationery inventory','Furniture inventory','Software licence counts without pricing','IT hardware asset list','Office supply records'] WHERE slug = 'internal-inventory';
UPDATE catalog_data_types SET examples = ARRAY['Employee engagement plans','Internal event schedules','Town hall agendas','Team building event plans','Internal celebration event details','Away day itineraries','Holiday party plans'] WHERE slug = 'internal-event-plans';
UPDATE catalog_data_types SET examples = ARRAY['Committee agendas','Governance meeting notes','Internal steering group minutes','Policy review summaries','Terms of reference','Board committee agendas without strategic content','Risk committee notes without sensitive ratings'] WHERE slug = 'internal-governance-notes';
UPDATE catalog_data_types SET examples = ARRAY['Basic vendor names','General supplier contact lists','Preferred vendor directory','Approved supplier registry','Category vendor lists','Vendor onboarding checklists','Supplier diversity data without commercial details'] WHERE slug = 'internal-vendor-list';
UPDATE catalog_data_types SET examples = ARRAY['App inventory without security details','General software list','SaaS application catalogue','Approved tools list','Internal tech stack overview','Software versions without vulnerabilities'] WHERE slug = 'internal-app-inventory';
UPDATE catalog_data_types SET examples = ARRAY['Non-sensitive status reports','Operational metrics','Team utilisation reports','SLA performance dashboards without customer data','Service delivery summaries','Capacity planning overviews','Helpdesk volume reports'] WHERE slug = 'internal-operational-reports';

-- ══ CONFIDENTIAL ══════════════════════════════════════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Customer names and account details','Customer contact records','Account ownership information','CRM account fields without PII','Customer relationship notes','Account activity summaries','Customer preference data','Account tier information'] WHERE slug = 'customer-business-data';
UPDATE catalog_data_types SET examples = ARRAY['Implementation plans','Customer-specific reports','Customer solution designs','Statement of work deliverables','Project documentation for a named customer','Customer architecture diagrams','Deployment guides for a specific client'] WHERE slug = 'customer-documents';
UPDATE catalog_data_types SET examples = ARRAY['Support tickets','Customer issue logs','Escalation records','Incident reports per customer','Feature request logs','Bug reports with customer context','Customer complaint records','SLA breach records'] WHERE slug = 'customer-support-cases';
UPDATE catalog_data_types SET examples = ARRAY['NDAs','Confidentiality agreements','Mutual NDA documents','Bilateral confidentiality agreements','Trial NDA schedules','Employee NDAs','Third-party NDA templates','Signed confidentiality deeds'] WHERE slug = 'ndas';
UPDATE catalog_data_types SET examples = ARRAY['Master service agreements','Statements of work','Customer agreements','Vendor supply agreements','Framework agreements','Enterprise licence agreements','Managed service contracts','Service schedules'] WHERE slug = 'master-service-agreements';
UPDATE catalog_data_types SET examples = ARRAY['Supplier agreements','Service contracts','SLAs','Outsourcing agreements','Subcontractor contracts','IT vendor contracts','Professional services agreements','Maintenance contracts','Hardware supply agreements'] WHERE slug = 'vendor-contracts';
UPDATE catalog_data_types SET examples = ARRAY['Pricing sheets','Discount models','Rate cards','Commercial terms','Volume pricing schedules','Partner pricing grids','List price matrices','Margin structures','Deal desk pricing','Contract price books'] WHERE slug = 'pricing-data';
UPDATE catalog_data_types SET examples = ARRAY['Sales proposals','Customer quotations','RFP responses','Commercial offers','Solution proposals','Business case presentations','Proof of concept proposals','Tender submissions','Contract renewal offers'] WHERE slug = 'sales-proposals';
UPDATE catalog_data_types SET examples = ARRAY['Opportunity reports','Pipeline forecasts','Deal strategy documents','CRM pipeline exports','Sales forecast spreadsheets','Win/loss analysis','Sales territory planning','Revenue projections per account'] WHERE slug = 'sales-pipeline';
UPDATE catalog_data_types SET examples = ARRAY['Vendor evaluations','Commercial comparisons','Supplier negotiations','RFP scoring matrices','Procurement decision papers','Vendor selection rationale','Supplier audit results','Procurement category strategies'] WHERE slug = 'procurement-data';
UPDATE catalog_data_types SET examples = ARRAY['Product roadmap decks','Feature launch plans','Unreleased feature details','R&D pipeline summaries','Product vision documents','Quarterly product plans','Initiative prioritisation lists','Feature feasibility studies'] WHERE slug = 'product-roadmap';
UPDATE catalog_data_types SET examples = ARRAY['Department strategy documents','Market expansion plans','Competitive positioning papers','Business unit strategies','Go-to-market strategy','Partnership strategies','Geographic expansion plans','Digital transformation roadmaps'] WHERE slug = 'business-strategy';
UPDATE catalog_data_types SET examples = ARRAY['Competitive intelligence reports','Customer segmentation studies','Market sizing analyses','Industry landscape reports','Competitor product analysis','Win/loss interview summaries','Customer survey results','Market entry research'] WHERE slug = 'market-research';
UPDATE catalog_data_types SET examples = ARRAY['HLD documents','LLD documents','As-built documentation','Deployment guides','Solution architecture documents','Integration design documents','Technical specification sheets','Test plans','UAT documentation'] WHERE slug = 'project-deliverables';
UPDATE catalog_data_types SET examples = ARRAY['Non-public revenue reports','Margin reports','Cost centre reports','Monthly management accounts','P&L by division','Cost allocation reports','Profitability analysis','Departmental budget actuals'] WHERE slug = 'internal-financial-reports';
UPDATE catalog_data_types SET examples = ARRAY['Budget planning documents','Forecast reports','Revenue analysis','Cost models','Annual budget packs','Rolling forecasts','Scenario planning models','Headcount planning','CapEx/OpEx plans','Three-year financial plans'] WHERE slug = 'budget-planning';
UPDATE catalog_data_types SET examples = ARRAY['Risk registers','Business risk ratings','Control gap summaries','Enterprise risk reports','Operational risk assessments','Third-party risk ratings','Risk appetite statements','Residual risk summaries'] WHERE slug = 'risk-registers';
UPDATE catalog_data_types SET examples = ARRAY['Internal audit evidence packs','Audit planning notes','Control testing workpapers','Audit findings drafts','Management response drafts','Control walkthroughs','Audit scoping documents'] WHERE slug = 'audit-preparation';
UPDATE catalog_data_types SET examples = ARRAY['Partner agreements','Channel strategy documents','Reseller details','Distribution partner data','Alliance frameworks','Technology partner contracts','Referral partner details','OEM agreements'] WHERE slug = 'partner-data';
UPDATE catalog_data_types SET examples = ARRAY['BCP documents','Recovery time objectives','Recovery point objectives','Business continuity tests','Crisis communications templates','Alternative site procedures','Operational resilience plans','Service continuity plans'] WHERE slug = 'business-continuity-plans';

-- ══ HIGHLY CONFIDENTIAL — Personal and Identity Data ══════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Social Security Numbers (SSN)','Aadhaar numbers','PAN (Permanent Account Number)','National Insurance numbers','Taxpayer identification numbers','National ID card numbers','SIN (Canada)','Medicare numbers','NRIC (Singapore)','Tax File Numbers (Australia)'] WHERE slug = 'government-identity-numbers';
UPDATE catalog_data_types SET examples = ARRAY['Passport number','Passport scan or photo','Visa details and stamps','Immigration documents','Travel document data','Passport expiry dates combined with name','Nationality combined with passport number'] WHERE slug = 'passport-data';
UPDATE catalog_data_types SET examples = ARRAY['Driver licence number','Scanned licence images','Licence class and restrictions','Driving record data','State ID numbers','Photo ID scans','International driving permits'] WHERE slug = 'driver-license-data';
UPDATE catalog_data_types SET examples = ARRAY['Date of birth combined with full name','DOB combined with national ID','Age and birth year with other identifiers','Date of birth in HR records','Birth date in insurance documents','Date of birth in loan applications'] WHERE slug = 'date-of-birth';
UPDATE catalog_data_types SET examples = ARRAY['Home address','Mailing address','Permanent residential address','Previous addresses','Geolocation data linked to individuals','Latitude/longitude linked to a named person','Address history records','Delivery address combined with customer name'] WHERE slug = 'personal-address';
UPDATE catalog_data_types SET examples = ARRAY['Personal mobile number','Personal email address','Home phone number','Emergency contact number','WhatsApp number linked to an individual','Personal contact details in HR files','Direct personal contact records'] WHERE slug = 'personal-contact-data';
UPDATE catalog_data_types SET examples = ARRAY['Fingerprint templates','Facial recognition templates','Iris scan data','Voiceprint records','Hand geometry measurements','Vein pattern data','Retinal scan data','Behavioural biometrics'] WHERE slug = 'biometric-identifiers';
UPDATE catalog_data_types SET examples = ARRAY['IP addresses linked to individuals','Cookie identifiers','Device fingerprints','Advertising IDs (IDFA, GAID)','Browser fingerprints','Mobile device identifiers','Persistent user tracking tokens','Cross-site tracking identifiers'] WHERE slug = 'online-identifiers';
UPDATE catalog_data_types SET examples = ARRAY['KYC forms','Proof of address documents','Selfie verification data','Liveness check results','Identity document scan plus selfie','Video verification recordings','ID verification audit logs'] WHERE slug = 'identity-verification-data';
UPDATE catalog_data_types SET examples = ARRAY['Employment verification records','Criminal background check results','Credit reference check outputs','Reference check responses','Education verification results','Right to work verification','DBS/CRB check certificates','Security clearance forms'] WHERE slug = 'background-verification';

-- ══ HIGHLY CONFIDENTIAL — Sensitive Personal / Special Category ══════════════

UPDATE catalog_data_types SET examples = ARRAY['Medical records','Prescriptions','Diagnosis reports','Lab test results','Disability records','GP referral letters','Hospital discharge summaries','Radiology reports','Immunisation records','Allergy records','Medical history files'] WHERE slug = 'health-data';
UPDATE catalog_data_types SET examples = ARRAY['Genetic test results','DNA profiles','Ancestry DNA data','Hereditary condition results','Pharmacogenomics data','Biomarker datasets linked to individuals','Gene sequencing outputs'] WHERE slug = 'genetic-data';
UPDATE catalog_data_types SET examples = ARRAY['Facial recognition templates stored for ID','Fingerprint templates used for authentication','Biometric login data','Iris templates used for access control','Biometric timekeeping records'] WHERE slug = 'biometric-identification';
UPDATE catalog_data_types SET examples = ARRAY['Religious affiliation records','Belief or faith-based membership records','Chaplaincy records','Spiritual care notes','Religious dietary requirement records','Religious observance records','Church membership data'] WHERE slug = 'religious-philosophical-data';
UPDATE catalog_data_types SET examples = ARRAY['Political party membership','Political opinion surveys','Voter preference records','Political affiliation forms','Campaign donation records','Political viewpoint assessments'] WHERE slug = 'political-opinion-data';
UPDATE catalog_data_types SET examples = ARRAY['Trade union membership lists','Union dues records','Shop steward records','Union membership application forms','Collective bargaining participant lists','Union consultation records'] WHERE slug = 'trade-union-data';
UPDATE catalog_data_types SET examples = ARRAY['Ethnicity data held for HR reporting','Racial origin forms','Diversity survey data where identifiable','Ethnic monitoring forms','Racial heritage data in employment records'] WHERE slug = 'racial-ethnic-data';
UPDATE catalog_data_types SET examples = ARRAY['Therapy session notes','Mental health assessments','Psychological evaluation reports','Psychiatric diagnosis records','Counselling session records','Mental health referral letters','EAP (Employee Assistance Programme) case notes','Stress or burnout assessment data'] WHERE slug = 'mental-health-data';

-- ══ HIGHLY CONFIDENTIAL — Payment and Financial Sensitive Data ════════════════

UPDATE catalog_data_types SET examples = ARRAY['Primary account number (PAN)','Cardholder name combined with PAN','Card expiry date combined with PAN','Card number exports','Tokenised card data before detokenisation','Masked PAN files with partial exposure','Payment card account lists'] WHERE slug = 'pci-cardholder-data';
UPDATE catalog_data_types SET examples = ARRAY['CVV/CVC/CID codes','PIN values','Full magnetic stripe data','Track 1 data','Track 2 data','Chip transaction data','CAV2/CVC2 codes','PIN verification values','Chip validation data'] WHERE slug = 'sensitive-auth-data';
UPDATE catalog_data_types SET examples = ARRAY['Bank account numbers','Sort codes','IBAN','SWIFT/BIC codes','Routing numbers','Bank statements','Direct debit mandates','ACH routing and account pairs','Bank account export files'] WHERE slug = 'bank-account-data';
UPDATE catalog_data_types SET examples = ARRAY['Payment authorisation records','Settlement files','Transaction processing logs','Chargeback records','Refund transaction files','Payment reconciliation exports','Batch payment files','SWIFT transfer records'] WHERE slug = 'payment-records';
UPDATE catalog_data_types SET examples = ARRAY['Individual tax returns','Corporate tax filings','Tax identification numbers','VAT/GST registration records','Tax assessment notices','HMRC correspondence','W-2 equivalents','1099 forms','Tax residency certificates','Transfer pricing documentation'] WHERE slug = 'tax-data';
UPDATE catalog_data_types SET examples = ARRAY['Payroll register files','Salary disbursement runs','Net pay files sent to banks','Payroll summaries by employee','Bonus payout files','Commission payment records','Payslip data files','Year-end P60/P11D files','Payroll reconciliation reports'] WHERE slug = 'payroll-files';
UPDATE catalog_data_types SET examples = ARRAY['Credit scores','Loan application forms','Credit card application data','Mortgage application files','Underwriting assessments','Credit limit decisions','Debt management plan records','Creditworthiness reports','Open banking data','FICO or equivalent score exports'] WHERE slug = 'loan-credit-data';
UPDATE catalog_data_types SET examples = ARRAY['Fraud case investigation files','Suspicious transaction reports (STRs)','AML investigation data','SAR (Suspicious Activity Reports)','Fraud pattern analysis','Disputed transaction records','Fraud ring investigation outputs','Financial intelligence reports'] WHERE slug = 'financial-fraud-data';

-- ══ HIGHLY CONFIDENTIAL — HR and Employee Sensitive Data ═════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Salary files','Bonus details','Pay slips','Compensation bands','Equity grant records','Incentive plan data','Total compensation statements','Benchmark salary surveys','Job level salary ranges','Confidential pay equity data'] WHERE slug = 'salary-compensation';
UPDATE catalog_data_types SET examples = ARRAY['Annual performance appraisals','Performance ratings','Promotion recommendations','Performance improvement plans (PIPs)','360-degree feedback data','Calibration session outputs','Talent review rankings','Succession planning assessments'] WHERE slug = 'performance-records';
UPDATE catalog_data_types SET examples = ARRAY['Written warnings','Final written warnings','Misconduct investigation outcomes','Disciplinary hearing records','Dismissal letters','Gross misconduct files','Appeal hearing records','Settlement agreement details'] WHERE slug = 'disciplinary-records';
UPDATE catalog_data_types SET examples = ARRAY['Employment contracts','Personal HR documents','Emergency contact details','Employment history records','Visa and work permit copies','Right to work documents','Signed offer letters','Employment verification letters','Benefits enrolment forms'] WHERE slug = 'employee-personal-file';
UPDATE catalog_data_types SET examples = ARRAY['Sick leave records','Medical certificates','Disability accommodation requests','Occupational health referrals','Maternity and paternity records','Long-term illness case files','Fit notes','Return-to-work plans','Workplace adjustment records'] WHERE slug = 'leave-medical-records';
UPDATE catalog_data_types SET examples = ARRAY['Employee complaints','Harassment and bullying reports','Whistleblower case records','Grievance hearing notes','Mediation records','Employee relations case files','Tribunal claim documents','Settlement details','ACAS early conciliation records'] WHERE slug = 'grievance-records';
UPDATE catalog_data_types SET examples = ARRAY['Redundancy selection criteria','Layoff planning documents','Redeployment lists','Voluntary redundancy offer details','Severance package calculations','Restructuring impact assessments','Confidential headcount reduction plans'] WHERE slug = 'workforce-reduction-data';

-- ══ HIGHLY CONFIDENTIAL — Customer-Sensitive Data ═════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['CRM full exports','Customer database dumps','Account data exports','Complete customer master file','Customer data warehouse extracts','Full customer contact database','Bulk email list with profile data','Aggregated customer PII files'] WHERE slug = 'bulk-customer-datasets';
UPDATE catalog_data_types SET examples = ARRAY['Customer full name plus email plus phone','Customer address combined with account ID','Date of birth with customer profile','Customer national ID in CRM','Combined PII fields from customer records','Customer identity bundle (name + address + DOB + contact)'] WHERE slug = 'customer-pii';
UPDATE catalog_data_types SET examples = ARRAY['Customer invoices','Billing records','Payment method details on file','Customer credit status','Outstanding balance records','Payment history by customer','Credit terms per account','Customer financial exposure data'] WHERE slug = 'customer-financial-info';
UPDATE catalog_data_types SET examples = ARRAY['Product usage logs per customer','Telemetry data linked to named customers','Behavioural analytics by user','Feature usage breakdown per org','Session recording data','Customer clickstream data','In-app activity logs linked to accounts'] WHERE slug = 'customer-usage-data';
UPDATE catalog_data_types SET examples = ARRAY['Customer login credentials','Password reset tokens','MFA status records','Session token data per user','Authentication event logs','Account takeover investigation data','Failed login attempts by customer'] WHERE slug = 'customer-auth-data';
UPDATE catalog_data_types SET examples = ARRAY['Customer network architecture diagrams','Tenant infrastructure details','Configuration exports for customer environments','Customer cloud topology files','Infrastructure inventory for named customers'] WHERE slug = 'customer-environment-data';
UPDATE catalog_data_types SET examples = ARRAY['Customer vulnerability disclosures','Customer security incident reports','Customer penetration test summaries','Security exceptions per customer','Audit evidence provided by customers','Customer security posture assessments'] WHERE slug = 'customer-security-info';

-- ══ HIGHLY CONFIDENTIAL — Legal and Compliance Sensitive Data ════════════════

UPDATE catalog_data_types SET examples = ARRAY['Legal case files','Claim documents','Legal evidence packs','Pre-litigation correspondence','Court submission drafts','Litigation hold notices','Legal exposure assessments','Defence strategy documents','Expert witness reports','Settlement negotiation records'] WHERE slug = 'litigation-data';
UPDATE catalog_data_types SET examples = ARRAY['Attorney-client email threads','Legal opinion letters','Counsel advice memos','Privileged review notes','Legal strategy documents under privilege','Outside counsel communications','Barristers or solicitors advice','Privileged deal analysis'] WHERE slug = 'legal-privileged-comms';
UPDATE catalog_data_types SET examples = ARRAY['Internal investigation case files','Misconduct investigation reports','Anti-corruption investigation data','Fraud investigation outputs','Ethics hotline case records','Investigation interview notes','CCTV footage for investigations','Digital forensics outputs'] WHERE slug = 'investigation-records';
UPDATE catalog_data_types SET examples = ARRAY['Non-public regulator responses','Examination reports from regulators','Regulatory inquiry submissions','Supervisory letters','FCA correspondence','ICO investigation responses','SEC examination materials','Consent order drafts','Regulatory settlement documents'] WHERE slug = 'regulatory-submissions';
UPDATE catalog_data_types SET examples = ARRAY['Protected disclosure reports','Ethics line complaints','Speak-up programme submissions','Whistleblower case files','Anonymous tip investigation records','Reported wrongdoing files','Retaliatory conduct investigation notes'] WHERE slug = 'whistleblower-reports';
UPDATE catalog_data_types SET examples = ARRAY['Data breach assessment files','Breach notification analysis','Impacted individual lists','Root cause investigation reports','Breach timeline documentation','ICO/DPA notification drafts','72-hour notification evidence packs','Breach remediation plans'] WHERE slug = 'data-breach-records';

-- ══ HIGHLY CONFIDENTIAL — Security-Sensitive Data ════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Network segmentation diagrams','Security zone maps','Trust boundary diagrams','Firewall rule architecture overviews','Security control paths','DMZ and internal network architecture','Zero trust boundary design','Security reference architecture docs'] WHERE slug = 'security-architecture';
UPDATE catalog_data_types SET examples = ARRAY['Vulnerability scanner results','CVE mapping and scoring','Exploitability details','CVSS score breakdowns','Internal vulnerability reports','Open vulnerability lists by asset','Patch gap reports','SAST/DAST scan outputs','Dependency vulnerability reports'] WHERE slug = 'vulnerability-reports';
UPDATE catalog_data_types SET examples = ARRAY['Penetration test final reports','Exploit paths identified','Attack chain diagrams','Proof-of-concept screenshots','Social engineering test results','Physical intrusion test findings','Red team findings','External attack surface reports','Internal network lateral movement paths'] WHERE slug = 'penetration-test-reports';
UPDATE catalog_data_types SET examples = ARRAY['Security incident reports','Attack timeline documentation','Attacker TTPs','Indicators of compromise (IOCs)','Forensic artefacts','Threat actor attribution data','Malware analysis outputs','Incident post-mortems','DFIR investigation packages'] WHERE slug = 'incident-response-data';
UPDATE catalog_data_types SET examples = ARRAY['SIEM alert logs with user activity','Authentication event logs','Privileged access session logs','User behaviour analytics (UBA) data','Failed authentication attempts','Lateral movement detection logs','Exfiltration detection logs','DNS query logs per user'] WHERE slug = 'siem-security-logs';
UPDATE catalog_data_types SET examples = ARRAY['Internal threat intelligence reports','Adversary observation data','IOCs before public release','OSINT findings on specific threats','Dark web monitoring findings','Threat actor profiles','Campaign analysis reports','Internal threat briefings'] WHERE slug = 'threat-intelligence';
UPDATE catalog_data_types SET examples = ARRAY['Security risk ratings by system','Control gap analysis reports','ISMS risk treatment plans','Residual risk acceptance records','Risk heat maps','Top security risk summaries','Cybersecurity maturity gap reports'] WHERE slug = 'risk-assessments-security';
UPDATE catalog_data_types SET examples = ARRAY['Privileged account access reports','Domain admin account lists','Service account inventory with access scope','Admin access certification reports','Standing privileged access records','PAM-managed account lists','Orphaned privileged account reports'] WHERE slug = 'access-review-reports';
UPDATE catalog_data_types SET examples = ARRAY['DR runbooks with system dependencies','Recovery procedures by application','Data centre failover procedures','RTO/RPO reference materials','Crisis escalation contact lists','Backup restoration procedures','DR test results and evidence','BCP-linked technical recovery steps'] WHERE slug = 'dr-runbooks';

-- ══ HIGHLY CONFIDENTIAL — Source Code and Engineering Data ═══════════════════

UPDATE catalog_data_types SET examples = ARRAY['Application source code repos','Backend service code','Frontend application code','Core business logic scripts','Microservice codebases','Monorepo exports','Proprietary algorithm implementations','Internal SDK source code','Plugin or extension source code'] WHERE slug = 'proprietary-source-code';
UPDATE catalog_data_types SET examples = ARRAY['Terraform configuration files','CloudFormation templates','Pulumi stacks','Kubernetes YAML manifests','Bicep and ARM templates','Ansible playbooks','Chef cookbooks','Puppet manifests','CDK infrastructure code'] WHERE slug = 'infrastructure-as-code';
UPDATE catalog_data_types SET examples = ARRAY['PowerShell deployment scripts','Bash automation scripts','Python provisioning scripts','Database migration scripts','Release automation scripts','CI/CD helper scripts','Data pipeline scripts','Infrastructure teardown scripts'] WHERE slug = 'automation-scripts';
UPDATE catalog_data_types SET examples = ARRAY['GitHub Actions workflow files','GitLab CI YAML definitions','Jenkinsfiles','CircleCI config','Azure Pipelines definitions','Bitbucket pipeline configs','TeamCity build configurations','Build and deploy pipeline specifications'] WHERE slug = 'cicd-pipeline-config';
UPDATE catalog_data_types SET examples = ARRAY['Internal REST API schemas','GraphQL schema definitions','Internal OpenAPI/Swagger specs','gRPC proto files','API integration contracts','Webhook payload schemas','Internal event schemas','Partner integration API specs'] WHERE slug = 'api-specifications';
UPDATE catalog_data_types SET examples = ARRAY['Core recommendation algorithm code','Proprietary scoring models','Search ranking algorithms','Fraud detection model logic','Pricing optimisation algorithms','Risk scoring logic','Personalisation engine implementations'] WHERE slug = 'product-algorithms';
UPDATE catalog_data_types SET examples = ARRAY['Sensitive table structures','Database entity-relationship diagrams','Stored procedure definitions','Data model diagrams','Database migration scripts with schema','Foreign key relationships','Index designs for sensitive tables','Data dictionary for regulated tables'] WHERE slug = 'database-schema';
UPDATE catalog_data_types SET examples = ARRAY['System architecture design docs','Engineering implementation specs','Technical approach documents','Component interaction diagrams','Integration design records','Data flow diagrams','Sequence diagrams','Technical decision records (TDRs)'] WHERE slug = 'technical-design-documents';

-- ══ HIGHLY CONFIDENTIAL — Intellectual Property and Research Data ═════════════

UPDATE catalog_data_types SET examples = ARRAY['R&D experiment results','Lab data','Research prototypes','Drug trial data','Materials science research','Product testing data','Clinical research data','Feasibility study results','Technology proof-of-concept outputs'] WHERE slug = 'research-data';
UPDATE catalog_data_types SET examples = ARRAY['Chemical formulas','Manufacturing recipes','Production process formulas','Pharmaceutical compound formulas','Cosmetic ingredient formulations','Food product recipes','Industrial process specifications','Material composition data'] WHERE slug = 'product-formulas';
UPDATE catalog_data_types SET examples = ARRAY['Patent application drafts','Invention disclosure forms','Provisional patent filings','Technical claims before filing','Patent search analysis','Pre-filing IP assessments','Innovation log entries awaiting filing'] WHERE slug = 'patent-drafts';
UPDATE catalog_data_types SET examples = ARRAY['Trained ML model weights','Proprietary foundation model assets','Custom fine-tuned model files','Training dataset summaries','Model architecture specifications','Evaluation benchmark results','Model performance reports','Proprietary prompt templates','RAG system configurations'] WHERE slug = 'ai-ml-models';
UPDATE catalog_data_types SET examples = ARRAY['Non-public business methods','Proprietary technical formulas','Confidential operational processes','Unique manufacturing techniques','Secret service delivery processes','Unrevealed competitive strategies','Trade secret registers'] WHERE slug = 'trade-secrets';

-- ══ HIGHLY CONFIDENTIAL — Operationally Sensitive Data ═══════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Production system configuration exports','Firewall rule exports','Proxy configuration files','Tenant configuration backups','Application configuration bundles','Cloud environment configurations','System hardening baselines','Network device configurations'] WHERE slug = 'production-configuration';
UPDATE catalog_data_types SET examples = ARRAY['Crown-jewel asset register','Critical application inventory','High-value data repository list','Business-critical system map','Essential infrastructure register','Core service dependency maps','Priority asset risk register'] WHERE slug = 'critical-system-inventory';
UPDATE catalog_data_types SET examples = ARRAY['Admin user access lists','Privileged role assignments','Superuser account inventory','Domain admin account lists','Root account registers','PAM-managed accounts list','Break-glass account registry','Privileged access scope per role'] WHERE slug = 'privileged-access-reports';
UPDATE catalog_data_types SET examples = ARRAY['High-risk vendor risk ratings','Third-party security control gaps','Vendor security assessment reports','Fourth-party risk findings','Supplier audit reports','Critical vendor exposure assessments','Cloud provider risk analysis','Outsourcing risk reports'] WHERE slug = 'vendor-risk-assessments';
UPDATE catalog_data_types SET examples = ARRAY['Emergency response procedures','Crisis escalation playbooks','Executive emergency contact lists','Crisis management team procedures','Business interruption response plans','Media and comms crisis scripts','Board crisis notification procedures','War room activation procedures'] WHERE slug = 'crisis-management-plans';

-- ══ SECRET — Credentials and Authentication Data ══════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['User account passwords','Admin console passwords','Database access passwords','Hardcoded passwords in code','Root system passwords','Service account passwords','Default device credentials','VPN access passwords','Wi-Fi network passwords','Backup system passwords','BIOS/UEFI passwords'] WHERE slug = 'passwords';
UPDATE catalog_data_types SET examples = ARRAY['Vault backup exports','CSV credential exports from vault','KeePass database exports (.kdbx)','1Password exports','LastPass credential exports','Bitwarden vault exports','HashiCorp Vault snapshot backups','Dashlane credential exports','CyberArk safe exports'] WHERE slug = 'password-vault-exports';
UPDATE catalog_data_types SET examples = ARRAY['Domain admin credentials','Root account credentials','Super admin passwords','Break-glass emergency accounts','Global administrator accounts','Enterprise admin accounts','Shared privileged accounts','MSOL (Microsoft Online) credentials','Cloud management console admin credentials','Tenant global admin details'] WHERE slug = 'privileged-credentials';
UPDATE catalog_data_types SET examples = ARRAY['Service account passwords','Robot process account credentials','Application-to-application credentials','Windows service account passwords','LDAP service bind credentials','Exchange service accounts','SharePoint service accounts','Scheduled task run-as credentials','Middleware service credentials'] WHERE slug = 'service-account-credentials';
UPDATE catalog_data_types SET examples = ARRAY['Database username and password pairs','JDBC/ODBC connection strings with credentials','MySQL root credentials','SQL Server sa credentials','MongoDB admin credentials','PostgreSQL superuser password','Redis AUTH password','Oracle system/sys credentials','Elasticsearch cluster credentials','Database admin password files'] WHERE slug = 'database-credentials';
UPDATE catalog_data_types SET examples = ARRAY['TOTP backup codes','SMS verification backup codes','Recovery seed phrases','Emergency MFA bypass codes','Authenticator app backup codes','Hardware token recovery keys','Account recovery emergency codes','Backup OTP sets','MFA bypass emergency procedures'] WHERE slug = 'mfa-recovery-data';
UPDATE catalog_data_types SET examples = ARRAY['Session cookies with auth tokens','Active session tokens','Issued bearer tokens','SAML assertion tokens','Kerberos service tickets','JWT session tokens','Auth session identifier cookies','Persistent login session tokens','Impersonation session tokens'] WHERE slug = 'session-credentials';

-- ══ SECRET — API Keys, Tokens, and Secrets ════════════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['AWS secret access keys','Cloud platform API keys','SaaS platform API keys','Payment gateway secret keys','Stripe secret key','Twilio auth token','SendGrid API key','OpenAI API key','Internal service API keys','Partner integration API keys','Third-party vendor API keys'] WHERE slug = 'api-keys';
UPDATE catalog_data_types SET examples = ARRAY['OAuth 2.0 access tokens','Bearer tokens in Authorization headers','GitHub personal access tokens','GitLab personal access tokens','Slack bot tokens','Google OAuth access tokens','Microsoft Graph access tokens','JWT tokens with active sessions','Bitbucket access tokens','Atlassian API tokens'] WHERE slug = 'access-tokens';
UPDATE catalog_data_types SET examples = ARRAY['OAuth 2.0 refresh tokens','Google long-lived refresh tokens','Microsoft refresh tokens','Offline access tokens','OIDC refresh tokens','Token rotation refresh credentials','Long-lived mobile app session tokens','Persistent OAuth refresh grants'] WHERE slug = 'refresh-tokens';
UPDATE catalog_data_types SET examples = ARRAY['OAuth app client secret values','Azure AD client secrets','Google OAuth 2.0 client secrets','GitHub OAuth app client secrets','Auth0 application client secrets','Okta client secrets','Ping Identity client secrets','AWS Cognito app client secrets','Keycloak client secrets'] WHERE slug = 'oauth-client-secrets';
UPDATE catalog_data_types SET examples = ARRAY['Webhook HMAC signing secrets','GitHub webhook secrets','Stripe webhook signing secrets','Slack signing secrets','Shopify webhook secrets','Twilio webhook auth tokens','Endpoint secret keys','Event delivery verification secrets','Payload signature keys'] WHERE slug = 'webhook-secrets';
UPDATE catalog_data_types SET examples = ARRAY['GitHub Actions encrypted secrets','GitLab CI/CD masked variables','Jenkins credential store entries','CircleCI context secrets','Azure DevOps pipeline secret variables','Bitbucket pipeline deployment variables','TeamCity stored credentials','ArgoCD secret references','Tekton pipeline secrets'] WHERE slug = 'cicd-pipeline-secrets';
UPDATE catalog_data_types SET examples = ARRAY['Slack bot and app tokens','GitHub integration tokens','Jira API tokens','Salesforce connected app tokens','Microsoft Graph integration tokens','Asana API keys','HubSpot API keys','Zendesk API tokens','Datadog API and application keys','PagerDuty integration keys','Confluence API tokens','Notion integration tokens'] WHERE slug = 'saas-integration-tokens';
UPDATE catalog_data_types SET examples = ARRAY['AWS access key ID and secret access key pair','Azure service principal credentials','GCP service account JSON key files','DigitalOcean personal access tokens','Cloudflare API tokens','Terraform Cloud API tokens','Pulumi access tokens','IBM Cloud API keys','Oracle Cloud auth tokens','Heroku API keys'] WHERE slug = 'cloud-access-keys';

-- ══ SECRET — Cryptographic and Key Material ═══════════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['RSA private keys','EC (elliptic curve) private keys','SSH private keys','TLS/SSL private keys','Code signing certificate private keys','PKCS#8 private key files','PEM-encoded private keys','X.509 certificate private keys','ECDSA private keys','EdDSA private keys'] WHERE slug = 'private-keys';
UPDATE catalog_data_types SET examples = ARRAY['AES symmetric encryption keys','Data encryption keys (DEKs)','Key encryption keys (KEKs)','Master encryption keys','BitLocker recovery keys','FileVault volume encryption keys','Database transparent data encryption keys','Volume encryption keys','Disk encryption credentials','HSM-generated symmetric keys'] WHERE slug = 'encryption-keys';
UPDATE catalog_data_types SET examples = ARRAY['AWS KMS exported key material','Azure Key Vault secret exports','Google Cloud KMS key exports','HashiCorp Vault seal key exports','Vault snapshot backups','Key management system backups','Exported certificate bundles','HSM key export packages'] WHERE slug = 'key-vault-exports';
UPDATE catalog_data_types SET examples = ARRAY['Code signing certificate private keys','Document digital signing keys','JWT RS256/ES256 signing keys','Apple code signing keys','Windows Authenticode signing certificates','npm package signing keys','Package signing and verification keys','DKIM private signing keys','S/MIME signing keys'] WHERE slug = 'signing-keys';
UPDATE catalog_data_types SET examples = ARRAY['SSH private key files (id_rsa, id_ed25519, id_ecdsa)','GitHub repository deploy keys','Server access private keys','Bastion host SSH keys','Jump server access keys','Automated deployment SSH keys','SSH agent forwarding keys','Ansible SSH connection keys'] WHERE slug = 'ssh-keys';
UPDATE catalog_data_types SET examples = ARRAY['PGP private keys','GPG private keys','GnuPG secret keyring exports','PGP private keyblock content','Email encryption and signing private keys','GPG detached signature keys','OpenPGP private key files','Encrypted email credential keys'] WHERE slug = 'pgp-keys';

-- ══ SECRET — High-Risk Certificate and Secret Files ══════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['.key files','.pem files with private key','.rsa private key files','.ppk files (PuTTY private key)','.id_rsa files','.p8 files','client.key','server.key','private.key','.der private key files','PKCS#1 key files'] WHERE slug = 'private-key-files';
UPDATE catalog_data_types SET examples = ARRAY['.jks (Java KeyStore) files','.p12 PKCS#12 bundles','.pfx certificate with private key','Android release keystore','cacerts files','truststore.jks','mykeystore.p12','Certificate + key bundle files','iOS distribution certificate files'] WHERE slug = 'keystore-files';
UPDATE catalog_data_types SET examples = ARRAY['.env files','.env.local','.env.production','.env.staging','.envrc files','secrets.yml with credentials','config.yml containing API keys','application.properties with passwords','config.json with secret values','.secret files','dotenv credential files'] WHERE slug = 'environment-files';
UPDATE catalog_data_types SET examples = ARRAY['~/.aws/credentials files','GCP service account JSON key files','Azure publish settings (.publishsettings)','gcloud auth credential files','Docker config.json with registry credentials','kubeconfig files with embedded access tokens','Terraform backend credential files','Cloud provider CLI auth files'] WHERE slug = 'cloud-credential-files';
UPDATE catalog_data_types SET examples = ARRAY['Kubernetes Secret YAML objects','kubeconfig files with cluster tokens','Service account token files','Docker registry imagePullSecrets','TLS certificate Secrets','Opaque Secret key-value pairs','Kubernetes sealed secret files','External Secrets operator CRDs','Flux or ArgoCD encrypted secret files'] WHERE slug = 'kubernetes-secrets';

-- ══ SECRET — Privileged Access and Administrative Data ═══════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Break-glass emergency credentials','Recovery administrator account details','Emergency access PAM passwords','Vault emergency access codes','Crisis admin override credentials','Disaster recovery admin passwords','Last-resort account access instructions'] WHERE slug = 'break-glass-accounts';
UPDATE catalog_data_types SET examples = ARRAY['Active Directory domain admin credentials','Privileged domain controller access details','Enterprise admin account details','Group Policy admin passwords','AD replication account credentials','Trust account credentials','Domain join account details'] WHERE slug = 'domain-admin-data';
UPDATE catalog_data_types SET examples = ARRAY['Linux/Unix root account passwords','AWS root account credentials','Cloud root console login details','Root SSH keys','Sudo configuration with root delegation','Root crontab credentials','Root access emergency instructions'] WHERE slug = 'root-access-details';
UPDATE catalog_data_types SET examples = ARRAY['MFA bypass techniques','SSO token interception methods','PAM bypass instructions','Authentication vulnerability exploit steps','SAML response manipulation details','Token forgery procedures','Kerberoasting techniques','Pass-the-hash method details','Golden ticket generation steps'] WHERE slug = 'auth-bypass-details';

-- ══ SECRET — Critical Security Data ══════════════════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Zero-day exploit code','Unpublished CVE exploitation steps','Unknown vulnerability proof-of-concept','Pre-disclosure vulnerability details','Unpatched remote code execution steps','Active zero-day analysis reports','Exploit development notes for unpatched flaws'] WHERE slug = 'zero-day-exploits';
UPDATE catalog_data_types SET examples = ARRAY['Working exploit scripts','Multi-stage attack chain code','Weaponised payloads','Malware samples for testing','Shellcode','Post-exploitation toolkit outputs','Ransomware test payloads','Reverse shell payloads','Credential harvesting tools'] WHERE slug = 'weaponized-exploits';
UPDATE catalog_data_types SET examples = ARRAY['DLP bypass techniques','EDR/AV evasion methods','IAM bypass instructions','Network segmentation bypass methods','Firewall rule bypass techniques','SIEM log tampering methods','Privileged escalation bypass steps','Security control circumvention guides'] WHERE slug = 'security-bypass-methods';
UPDATE catalog_data_types SET examples = ARRAY['Unpublished domain compromise paths','Crown-jewel system takeover findings','Full AD compromise walkthrough','Critical infrastructure takeover steps','Tier-0 asset compromise paths','Unreported critical CVE in production','Business-critical chain exploit findings'] WHERE slug = 'red-team-findings';

-- ══ SECRET — Executive, Board, M&A, and Market-Sensitive Data ═════════════════

UPDATE catalog_data_types SET examples = ARRAY['Acquisition target analysis','M&A negotiation documents','Due diligence materials','Transaction data room contents','Term sheet drafts','Merger integration plans','Target company valuation models','Post-merger synergy plans','Confidential information memoranda (CIM)','NDA-covered deal documents'] WHERE slug = 'ma-documents';
UPDATE catalog_data_types SET examples = ARRAY['Board meeting packs','Board minutes','Board strategic decisions','Non-public board presentations','Committee chair reports','Director papers','Board risk reports','Remuneration committee papers','Audit committee findings','Governance committee papers'] WHERE slug = 'board-papers';
UPDATE catalog_data_types SET examples = ARRAY['Pre-release earnings results','Undisclosed revenue figures','Material financial disclosures before announcement','Quarterly earnings drafts','Profit warnings before release','Capital raise plans before announcement','Non-public dividend decisions','Pre-clearance trading information'] WHERE slug = 'unreleased-financial-results';
UPDATE catalog_data_types SET examples = ARRAY['Confidential layoff planning documents','Business unit closure plans','Workforce reduction target lists','Major reorganisation proposals','Site closure plans','Leadership team restructuring details','Divisional spin-off plans','Workforce right-sizing models'] WHERE slug = 'strategic-restructuring';

-- ══ SECRET — Crown-Jewel Intellectual Property ═══════════════════════════════

UPDATE catalog_data_types SET examples = ARRAY['Core differentiating algorithm implementations','Proprietary ranking or scoring algorithms','Unique optimisation logic','Unreleased breakthrough algorithms','Competitive advantage algorithmic IP','Central business logic trade secrets','High-value proprietary models'] WHERE slug = 'crown-jewel-algorithms';
UPDATE catalog_data_types SET examples = ARRAY['Foundation model weights','High-value fine-tuned model checkpoints','Proprietary training dataset summaries','Unreleased model architectures','Flagship AI product model files','Core ML inference model weights','Confidential model performance benchmarks'] WHERE slug = 'critical-ml-models';
UPDATE catalog_data_types SET examples = ARRAY['High-value chemical formulas','Secret manufacturing processes','Confidential product composition data','Scientific breakthrough details','Secret operational formulas','Proprietary production techniques','Core trade secret registers'] WHERE slug = 'crown-jewel-trade-secrets';
UPDATE catalog_data_types SET examples = ARRAY['Major invention disclosures before filing','Breakthrough invention documentation','Critical innovation before legal protection','Novel technology concepts pre-patent','Patentable discovery details','Pre-filing technical specifications for critical IP'] WHERE slug = 'unfiled-critical-patents';
