-- ─────────────────────────────────────────────────────────────────────────────
-- 024_destination_applications.sql
-- App catalog for destination application search + applications column on destinations.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS catalog_apps (
  id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name     TEXT NOT NULL,
  category TEXT,
  vendor   TEXT
);

ALTER TABLE catalog_apps ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_read" ON catalog_apps FOR SELECT USING (true);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS catalog_apps_name_trgm ON catalog_apps USING gin(name gin_trgm_ops);
CREATE UNIQUE INDEX IF NOT EXISTS catalog_apps_name_unique ON catalog_apps (lower(name));

-- ─── Seed data ────────────────────────────────────────────────────────────────

INSERT INTO catalog_apps (name, category, vendor) VALUES
-- SaaS & Productivity
('Microsoft 365', 'saas', 'Microsoft'),
('Google Workspace', 'saas', 'Google'),
('Notion', 'saas', 'Notion Labs'),
('Asana', 'saas', 'Asana'),
('Monday.com', 'saas', 'Monday.com'),
('ClickUp', 'saas', 'ClickUp'),
('Airtable', 'saas', 'Airtable'),
('Trello', 'saas', 'Atlassian'),
('Basecamp', 'saas', 'Basecamp'),
('Wrike', 'saas', 'Wrike'),
('Smartsheet', 'saas', 'Smartsheet'),
('Todoist', 'saas', 'Doist'),
('Evernote', 'saas', 'Evernote'),
('Coda', 'saas', 'Coda'),
('Quip', 'saas', 'Salesforce'),
('Nuclino', 'saas', 'Nuclino'),
('Tettra', 'saas', 'Tettra'),
('Guru', 'saas', 'Guru'),
('Slab', 'saas', 'Slab'),
('Slite', 'saas', 'Slite'),
('Linear', 'saas', 'Linear'),
('Height', 'saas', 'Height'),
('Plane', 'saas', 'Plane'),
('Taskade', 'saas', 'Taskade'),
('Craft', 'saas', 'Craft Docs'),
('Bit.ai', 'saas', 'Bit.ai'),
('Almanac', 'saas', 'Almanac'),
('Range', 'saas', 'Range'),
('Confluence', 'saas', 'Atlassian'),
('SharePoint', 'saas', 'Microsoft'),

-- Collaboration & Messaging
('Slack', 'collaboration', 'Salesforce'),
('Microsoft Teams', 'collaboration', 'Microsoft'),
('Google Chat', 'collaboration', 'Google'),
('Discord', 'collaboration', 'Discord'),
('Mattermost', 'collaboration', 'Mattermost'),
('Rocket.Chat', 'collaboration', 'Rocket.Chat'),
('Telegram', 'collaboration', 'Telegram'),
('Flock', 'collaboration', 'Flock'),
('Twist', 'collaboration', 'Doist'),
('Lark', 'collaboration', 'ByteDance'),
('Chanty', 'collaboration', 'Chanty'),
('Workplace by Meta', 'collaboration', 'Meta'),
('Pumble', 'collaboration', 'Pumble'),
('Webex Teams', 'collaboration', 'Cisco'),
('Google Currents', 'collaboration', 'Google'),
('Glip', 'collaboration', 'RingCentral'),
('Yammer', 'collaboration', 'Microsoft'),
('Cisco Jabber', 'collaboration', 'Cisco'),

-- Cloud Storage
('OneDrive', 'storage', 'Microsoft'),
('Google Drive', 'storage', 'Google'),
('Dropbox', 'storage', 'Dropbox'),
('Box', 'storage', 'Box'),
('iCloud Drive', 'storage', 'Apple'),
('Egnyte', 'storage', 'Egnyte'),
('Citrix ShareFile', 'storage', 'Citrix'),
('Sync.com', 'storage', 'Sync.com'),
('pCloud', 'storage', 'pCloud'),
('MEGA', 'storage', 'MEGA'),
('Backblaze B2', 'storage', 'Backblaze'),
('Wasabi', 'storage', 'Wasabi'),
('AWS S3', 'storage', 'Amazon'),
('Azure Blob Storage', 'storage', 'Microsoft'),
('Google Cloud Storage', 'storage', 'Google'),
('Dropbox Business', 'storage', 'Dropbox'),
('Box Enterprise', 'storage', 'Box'),
('Tresorit', 'storage', 'Tresorit'),
('SpiderOak', 'storage', 'SpiderOak'),

-- AI Tools
('ChatGPT', 'ai', 'OpenAI'),
('Claude', 'ai', 'Anthropic'),
('Google Gemini', 'ai', 'Google'),
('Microsoft Copilot', 'ai', 'Microsoft'),
('Perplexity AI', 'ai', 'Perplexity'),
('Midjourney', 'ai', 'Midjourney'),
('DALL-E', 'ai', 'OpenAI'),
('GitHub Copilot', 'ai', 'GitHub'),
('Amazon Q', 'ai', 'Amazon'),
('Cursor', 'ai', 'Anysphere'),
('Grok', 'ai', 'xAI'),
('Character AI', 'ai', 'Character.AI'),
('Poe', 'ai', 'Quora'),
('You.com', 'ai', 'You.com'),
('Jasper', 'ai', 'Jasper'),
('Copy.ai', 'ai', 'Copy.ai'),
('Writesonic', 'ai', 'Writesonic'),
('Grammarly', 'ai', 'Grammarly'),
('Otter.ai', 'ai', 'Otter.ai'),
('Fireflies.ai', 'ai', 'Fireflies.ai'),
('Notion AI', 'ai', 'Notion Labs'),
('Runway', 'ai', 'Runway'),
('Stable Diffusion', 'ai', 'Stability AI'),
('Cohere', 'ai', 'Cohere'),
('Hugging Face', 'ai', 'Hugging Face'),
('Inflection Pi', 'ai', 'Inflection AI'),
('Salesforce Einstein', 'ai', 'Salesforce'),
('IBM Watson', 'ai', 'IBM'),
('Google Bard', 'ai', 'Google'),
('Bing AI', 'ai', 'Microsoft'),

-- Dev & Code
('GitHub', 'dev', 'Microsoft'),
('GitLab', 'dev', 'GitLab'),
('Bitbucket', 'dev', 'Atlassian'),
('Azure DevOps', 'dev', 'Microsoft'),
('Jira', 'dev', 'Atlassian'),
('Jenkins', 'dev', 'CloudBees'),
('CircleCI', 'dev', 'CircleCI'),
('Travis CI', 'dev', 'Travis CI'),
('GitHub Actions', 'dev', 'GitHub'),
('GitLab CI/CD', 'dev', 'GitLab'),
('ArgoCD', 'dev', 'CNCF'),
('Terraform Cloud', 'dev', 'HashiCorp'),
('SonarQube', 'dev', 'SonarSource'),
('Snyk', 'dev', 'Snyk'),
('Veracode', 'dev', 'Broadcom'),
('Docker Hub', 'dev', 'Docker'),
('npm Registry', 'dev', 'npm'),
('PyPI', 'dev', 'Python'),
('Artifactory', 'dev', 'JFrog'),
('HashiCorp Vault', 'dev', 'HashiCorp'),
('Cloudflare', 'dev', 'Cloudflare'),
('Vercel', 'dev', 'Vercel'),
('Netlify', 'dev', 'Netlify'),
('Heroku', 'dev', 'Salesforce'),
('Railway', 'dev', 'Railway'),
('Render', 'dev', 'Render'),
('Supabase', 'dev', 'Supabase'),
('PlanetScale', 'dev', 'PlanetScale'),
('Fly.io', 'dev', 'Fly.io'),
('Datadog', 'dev', 'Datadog'),
('AWS CodeCommit', 'dev', 'Amazon'),
('Checkmarx', 'dev', 'Checkmarx'),
('GitGuardian', 'dev', 'GitGuardian'),
('Dependabot', 'dev', 'GitHub'),
('Nx Cloud', 'dev', 'Nrwl'),
('Buildkite', 'dev', 'Buildkite'),
('TeamCity', 'dev', 'JetBrains'),
('Bamboo', 'dev', 'Atlassian'),

-- Email
('Gmail', 'email', 'Google'),
('Microsoft Outlook', 'email', 'Microsoft'),
('Yahoo Mail', 'email', 'Yahoo'),
('ProtonMail', 'email', 'Proton'),
('Zoho Mail', 'email', 'Zoho'),
('Fastmail', 'email', 'Fastmail'),
('Tutanota', 'email', 'Tuta'),
('Hey', 'email', 'Basecamp'),
('SendGrid', 'email', 'Twilio'),
('Mailgun', 'email', 'Mailgun'),
('Postmark', 'email', 'Wildbit'),
('Amazon SES', 'email', 'Amazon'),
('Mailchimp Transactional', 'email', 'Intuit'),
('SparkPost', 'email', 'MessageBird'),
('Brevo', 'email', 'Brevo'),

-- HR & People
('Workday', 'hr', 'Workday'),
('SAP SuccessFactors', 'hr', 'SAP'),
('Darwinbox', 'hr', 'Darwinbox'),
('BambooHR', 'hr', 'BambooHR'),
('HiBob', 'hr', 'HiBob'),
('Personio', 'hr', 'Personio'),
('Rippling', 'hr', 'Rippling'),
('Gusto', 'hr', 'Gusto'),
('ADP Workforce Now', 'hr', 'ADP'),
('Paychex', 'hr', 'Paychex'),
('Deel', 'hr', 'Deel'),
('Remote', 'hr', 'Remote'),
('Oyster HR', 'hr', 'Oyster'),
('Lattice', 'hr', 'Lattice'),
('Culture Amp', 'hr', 'Culture Amp'),
('Leapsome', 'hr', 'Leapsome'),
('15Five', 'hr', '15Five'),
('Paylocity', 'hr', 'Paylocity'),
('Greenhouse', 'hr', 'Greenhouse'),
('Lever', 'hr', 'Lever'),
('Workable', 'hr', 'Workable'),
('SmartRecruiters', 'hr', 'SmartRecruiters'),
('iCIMS', 'hr', 'iCIMS'),
('Taleo', 'hr', 'Oracle'),
('Ceridian Dayforce', 'hr', 'Ceridian'),

-- Finance & ERP
('SAP ERP', 'finance', 'SAP'),
('Oracle NetSuite', 'finance', 'Oracle'),
('Microsoft Dynamics 365 Finance', 'finance', 'Microsoft'),
('Sage Intacct', 'finance', 'Sage'),
('QuickBooks', 'finance', 'Intuit'),
('Xero', 'finance', 'Xero'),
('FreshBooks', 'finance', 'FreshBooks'),
('Coupa', 'finance', 'Coupa'),
('Tipalti', 'finance', 'Tipalti'),
('SAP Concur', 'finance', 'SAP'),
('Expensify', 'finance', 'Expensify'),
('Brex', 'finance', 'Brex'),
('Airbase', 'finance', 'Airbase'),
('Ramp', 'finance', 'Ramp'),
('Stripe', 'finance', 'Stripe'),
('PayPal', 'finance', 'PayPal'),
('Square', 'finance', 'Block'),
('Zuora', 'finance', 'Zuora'),
('Chargebee', 'finance', 'Chargebee'),
('Avalara', 'finance', 'Avalara'),
('Workiva', 'finance', 'Workiva'),
('BlackLine', 'finance', 'BlackLine'),
('Kyriba', 'finance', 'Kyriba'),
('Anaplan', 'finance', 'Anaplan'),
('Adaptive Insights', 'finance', 'Workday'),
('Oracle ERP Cloud', 'finance', 'Oracle'),
('Infor', 'finance', 'Infor'),

-- CRM & Sales
('Salesforce', 'crm', 'Salesforce'),
('HubSpot CRM', 'crm', 'HubSpot'),
('Microsoft Dynamics CRM', 'crm', 'Microsoft'),
('Zoho CRM', 'crm', 'Zoho'),
('Pipedrive', 'crm', 'Pipedrive'),
('Freshsales', 'crm', 'Freshworks'),
('Close.io', 'crm', 'Close'),
('Salesloft', 'crm', 'Salesloft'),
('Outreach', 'crm', 'Outreach'),
('Apollo.io', 'crm', 'Apollo'),
('Gong', 'crm', 'Gong'),
('Chorus.ai', 'crm', 'ZoomInfo'),
('ZoomInfo', 'crm', 'ZoomInfo'),
('LinkedIn Sales Navigator', 'crm', 'LinkedIn'),
('Drift', 'crm', 'Salesloft'),
('Intercom', 'crm', 'Intercom'),
('Zendesk Sell', 'crm', 'Zendesk'),
('Copper', 'crm', 'Copper'),
('Insightly', 'crm', 'Insightly'),
('Nutshell', 'crm', 'Nutshell'),
('Clari', 'crm', 'Clari'),
('Revenue.io', 'crm', 'Revenue.io'),

-- Security
('Okta', 'security', 'Okta'),
('Microsoft Azure AD', 'security', 'Microsoft'),
('Auth0', 'security', 'Okta'),
('Ping Identity', 'security', 'Ping Identity'),
('CrowdStrike', 'security', 'CrowdStrike'),
('SentinelOne', 'security', 'SentinelOne'),
('Carbon Black', 'security', 'VMware'),
('Darktrace', 'security', 'Darktrace'),
('Qualys', 'security', 'Qualys'),
('Tenable', 'security', 'Tenable'),
('Rapid7', 'security', 'Rapid7'),
('Palo Alto Prisma Cloud', 'security', 'Palo Alto Networks'),
('Fortinet', 'security', 'Fortinet'),
('Sophos', 'security', 'Sophos'),
('Proofpoint', 'security', 'Proofpoint'),
('Mimecast', 'security', 'Mimecast'),
('Abnormal Security', 'security', 'Abnormal Security'),
('Varonis', 'security', 'Varonis'),
('CyberArk', 'security', 'CyberArk'),
('BeyondTrust', 'security', 'BeyondTrust'),
('1Password', 'security', '1Password'),
('LastPass', 'security', 'LogMeIn'),
('Bitwarden', 'security', 'Bitwarden'),
('Duo Security', 'security', 'Cisco'),
('Cybereason', 'security', 'Cybereason'),
('Vectra AI', 'security', 'Vectra AI'),
('Illumio', 'security', 'Illumio'),
('Netskope', 'security', 'Netskope'),
('Zscaler', 'security', 'Zscaler'),
('Wiz', 'security', 'Wiz'),
('Orca Security', 'security', 'Orca Security'),
('Lacework', 'security', 'Lacework'),

-- ITSM
('ServiceNow', 'itsm', 'ServiceNow'),
('Jira Service Management', 'itsm', 'Atlassian'),
('Zendesk', 'itsm', 'Zendesk'),
('Freshdesk', 'itsm', 'Freshworks'),
('ManageEngine ServiceDesk Plus', 'itsm', 'Zoho'),
('BMC Helix', 'itsm', 'BMC'),
('Ivanti', 'itsm', 'Ivanti'),
('TOPdesk', 'itsm', 'TOPdesk'),
('HappyFox', 'itsm', 'HappyFox'),
('SolarWinds Service Desk', 'itsm', 'SolarWinds'),
('Cherwell', 'itsm', 'Ivanti'),
('SysAid', 'itsm', 'SysAid'),
('Spiceworks', 'itsm', 'Spiceworks'),
('Kayako', 'itsm', 'Kayako'),

-- Video & Meetings
('Zoom', 'video', 'Zoom'),
('Google Meet', 'video', 'Google'),
('Webex', 'video', 'Cisco'),
('GoToMeeting', 'video', 'LogMeIn'),
('BlueJeans', 'video', 'Verizon'),
('RingCentral Video', 'video', 'RingCentral'),
('8x8 Video', 'video', '8x8'),
('Vonage Meetings', 'video', 'Vonage'),
('Loom', 'video', 'Loom'),
('Vimeo', 'video', 'Vimeo'),
('Wistia', 'video', 'Wistia'),
('Brightcove', 'video', 'Brightcove'),
('StreamYard', 'video', 'StreamYard'),
('Riverside', 'video', 'Riverside'),
('Livestorm', 'video', 'Livestorm'),

-- Analytics & BI
('Microsoft Power BI', 'analytics', 'Microsoft'),
('Tableau', 'analytics', 'Salesforce'),
('Looker', 'analytics', 'Google'),
('Google Analytics', 'analytics', 'Google'),
('Adobe Analytics', 'analytics', 'Adobe'),
('Mixpanel', 'analytics', 'Mixpanel'),
('Amplitude', 'analytics', 'Amplitude'),
('Segment', 'analytics', 'Twilio'),
('Heap', 'analytics', 'Contentsquare'),
('Hotjar', 'analytics', 'Hotjar'),
('FullStory', 'analytics', 'FullStory'),
('Domo', 'analytics', 'Domo'),
('Qlik', 'analytics', 'Qlik'),
('MicroStrategy', 'analytics', 'MicroStrategy'),
('Mode Analytics', 'analytics', 'Mode'),
('Metabase', 'analytics', 'Metabase'),
('Grafana', 'analytics', 'Grafana Labs'),
('Splunk', 'analytics', 'Cisco'),
('New Relic', 'analytics', 'New Relic'),
('Dynatrace', 'analytics', 'Dynatrace'),
('AppDynamics', 'analytics', 'Cisco'),
('Elastic', 'analytics', 'Elastic'),

-- Marketing
('HubSpot Marketing', 'marketing', 'HubSpot'),
('Marketo', 'marketing', 'Adobe'),
('Pardot', 'marketing', 'Salesforce'),
('Mailchimp', 'marketing', 'Intuit'),
('Klaviyo', 'marketing', 'Klaviyo'),
('Campaign Monitor', 'marketing', 'Campaign Monitor'),
('Constant Contact', 'marketing', 'Constant Contact'),
('ActiveCampaign', 'marketing', 'ActiveCampaign'),
('Hootsuite', 'marketing', 'Hootsuite'),
('Buffer', 'marketing', 'Buffer'),
('Sprout Social', 'marketing', 'Sprout Social'),
('Semrush', 'marketing', 'Semrush'),
('Ahrefs', 'marketing', 'Ahrefs'),
('Moz', 'marketing', 'Moz'),
('Adobe Creative Cloud', 'marketing', 'Adobe'),
('Canva', 'marketing', 'Canva'),
('Figma', 'marketing', 'Figma'),

-- Legal & Compliance
('DocuSign', 'legal', 'DocuSign'),
('Adobe Sign', 'legal', 'Adobe'),
('PandaDoc', 'legal', 'PandaDoc'),
('Ironclad', 'legal', 'Ironclad'),
('OneTrust', 'legal', 'OneTrust'),
('TrustArc', 'legal', 'TrustArc'),
('BigID', 'legal', 'BigID'),
('Drata', 'legal', 'Drata'),
('Vanta', 'legal', 'Vanta'),
('Sprinto', 'legal', 'Sprinto'),
('Secureframe', 'legal', 'Secureframe'),
('Hyperproof', 'legal', 'Hyperproof'),
('LogicGate', 'legal', 'LogicGate'),
('Clio', 'legal', 'Clio'),
('Relativity', 'legal', 'Relativity'),

-- Data & Integration
('Snowflake', 'data', 'Snowflake'),
('Google BigQuery', 'data', 'Google'),
('Databricks', 'data', 'Databricks'),
('Amazon Redshift', 'data', 'Amazon'),
('Azure Synapse Analytics', 'data', 'Microsoft'),
('dbt Cloud', 'data', 'dbt Labs'),
('Fivetran', 'data', 'Fivetran'),
('Airbyte', 'data', 'Airbyte'),
('Stitch Data', 'data', 'Talend'),
('MuleSoft', 'data', 'Salesforce'),
('Workato', 'data', 'Workato'),
('Zapier', 'data', 'Zapier'),
('Make', 'data', 'Celonis'),
('Dell Boomi', 'data', 'Dell'),
('Informatica', 'data', 'Informatica'),
('Talend', 'data', 'Qlik'),
('Confluent', 'data', 'Confluent'),
('Twilio', 'data', 'Twilio'),
('Census', 'data', 'Census'),
('Hightouch', 'data', 'Hightouch'),
('Starburst', 'data', 'Starburst'),
('Trino', 'data', 'Trino'),
('Apache Kafka', 'data', 'Apache'),
('RabbitMQ', 'data', 'Broadcom'),

-- Cloud Platforms
('Amazon Web Services', 'cloud', 'Amazon'),
('Microsoft Azure', 'cloud', 'Microsoft'),
('Google Cloud Platform', 'cloud', 'Google'),
('DigitalOcean', 'cloud', 'DigitalOcean'),
('Linode', 'cloud', 'Akamai'),
('Vultr', 'cloud', 'Vultr'),
('IBM Cloud', 'cloud', 'IBM'),
('Oracle Cloud', 'cloud', 'Oracle'),
('Alibaba Cloud', 'cloud', 'Alibaba'),
('Cloudflare Workers', 'cloud', 'Cloudflare'),
('Hetzner Cloud', 'cloud', 'Hetzner'),
('Scaleway', 'cloud', 'Scaleway'),
('Fastly', 'cloud', 'Fastly'),
('Akamai', 'cloud', 'Akamai'),
('OVHcloud', 'cloud', 'OVH'),

-- Design & Creative
('Miro', 'design', 'Miro'),
('Lucidchart', 'design', 'Lucid'),
('Whimsical', 'design', 'Whimsical'),
('InVision', 'design', 'InVision'),
('Zeplin', 'design', 'Zeplin'),
('Sketch', 'design', 'Sketch'),
('Adobe XD', 'design', 'Adobe'),
('Framer', 'design', 'Framer'),
('Webflow', 'design', 'Webflow'),
('Lottiefiles', 'design', 'LottieFiles'),

-- Customer Success
('Gainsight', 'success', 'Gainsight'),
('ChurnZero', 'success', 'ChurnZero'),
('Totango', 'success', 'Totango'),
('Planhat', 'success', 'Planhat'),
('Pendo', 'success', 'Pendo'),
('Appcues', 'success', 'Appcues'),
('WalkMe', 'success', 'WalkMe'),
('UserVoice', 'success', 'UserVoice'),

-- Monitoring & Ops
('PagerDuty', 'ops', 'PagerDuty'),
('OpsGenie', 'ops', 'Atlassian'),
('VictorOps', 'ops', 'Splunk'),
('xMatters', 'ops', 'xMatters'),
('Statuspage', 'ops', 'Atlassian'),
('Prometheus', 'ops', 'CNCF'),
('Kibana', 'ops', 'Elastic'),
('Sentry', 'ops', 'Sentry'),
('Rollbar', 'ops', 'Rollbar'),
('Honeybadger', 'ops', 'Honeybadger'),
('SolarWinds', 'ops', 'SolarWinds'),
('Nagios', 'ops', 'Nagios'),
('Zabbix', 'ops', 'Zabbix'),
('New Relic One', 'ops', 'New Relic'),

-- File Transfer & MFT
('MOVEit', 'transfer', 'Progress'),
('GoAnywhere MFT', 'transfer', 'HelpSystems'),
('WeTransfer', 'transfer', 'WeTransfer'),
('Hightail', 'transfer', 'Hightail'),
('FileZilla', 'transfer', 'FileZilla'),
('Globalscape EFT', 'transfer', 'HelpSystems'),
('Axway MFT', 'transfer', 'Axway'),
('IBM Sterling', 'transfer', 'IBM'),

-- Communication & Telephony
('RingCentral', 'communication', 'RingCentral'),
('Dialpad', 'communication', 'Dialpad'),
('Aircall', 'communication', 'Aircall'),
('Talkdesk', 'communication', 'Talkdesk'),
('Five9', 'communication', 'Five9'),
('Genesys', 'communication', 'Genesys'),
('NICE CXone', 'communication', 'NICE'),

-- E-commerce & CMS
('Shopify', 'ecommerce', 'Shopify'),
('WooCommerce', 'ecommerce', 'Automattic'),
('Magento', 'ecommerce', 'Adobe'),
('BigCommerce', 'ecommerce', 'BigCommerce'),
('Contentful', 'ecommerce', 'Contentful'),
('Sanity', 'ecommerce', 'Sanity'),
('Prismic', 'ecommerce', 'Prismic'),
('WordPress', 'ecommerce', 'Automattic'),
('Squarespace', 'ecommerce', 'Squarespace'),
('Wix', 'ecommerce', 'Wix')

ON CONFLICT (lower(name)) DO NOTHING;

-- ─── Add applications column to org_destinations ──────────────────────────────

ALTER TABLE org_destinations
  ADD COLUMN IF NOT EXISTS applications TEXT[] NOT NULL DEFAULT '{}';
