-- ─────────────────────────────────────────────────────────────────────────────
-- 030_identity_catalog.sql
-- Identity & User Context Layer — system catalog of 36 standard values across
-- 4 DLP identity context fields:
--   business_function | privilege_level | employment_type | user_lifecycle_status
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS catalog_identity_values (
  id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  field_name  TEXT        NOT NULL CHECK (field_name IN (
    'business_function', 'privilege_level', 'employment_type', 'user_lifecycle_status'
  )),
  value_slug  TEXT        UNIQUE NOT NULL,
  value_name  TEXT        NOT NULL,
  description TEXT,
  risk_level  TEXT        NOT NULL DEFAULT 'medium' CHECK (risk_level IN (
    'critical', 'high', 'medium', 'low'
  )),
  risk_note   TEXT,
  priority    INT         NOT NULL DEFAULT 50,
  active      BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE catalog_identity_values ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_read" ON catalog_identity_values FOR SELECT USING (true);

-- ─── Seed: Business Function (16 values) ─────────────────────────────────────

INSERT INTO catalog_identity_values
  (field_name, value_slug, value_name, description, risk_level, risk_note, priority)
VALUES
  ('business_function', 'bf_hr',
    'HR',
    'Human resources and employee lifecycle teams.',
    'medium',
    'Routinely handles sensitive employee records, payroll, and benefits data. Sharing outside expected workflows or to personal destinations is high risk.',
    10),
  ('business_function', 'bf_finance',
    'Finance',
    'Finance, accounting, billing, treasury, audit, and reporting teams.',
    'medium',
    'Handles invoices, payment data, financial reports, and tax data. External movement requires strong destination validation.',
    20),
  ('business_function', 'bf_legal',
    'Legal',
    'Legal, compliance, contract, litigation, and regulatory teams.',
    'medium',
    'Handles privileged legal documents, regulatory submissions, and contracts. Unexpected external sharing is high risk.',
    30),
  ('business_function', 'bf_sales',
    'Sales',
    'Sales, account management, business development, and revenue teams.',
    'medium',
    'Handles customer contacts, pricing, and pipeline reports. External sharing of pricing or customer data requires monitoring.',
    40),
  ('business_function', 'bf_marketing',
    'Marketing',
    'Marketing, communications, brand, demand generation, and campaign teams.',
    'low',
    'Handles campaign data and market research. Oversharing of customer segments to external parties requires monitoring.',
    50),
  ('business_function', 'bf_engineering',
    'Engineering',
    'Software engineering, product engineering, DevOps, and technical development teams.',
    'medium',
    'Handles source code, repositories, and technical designs. External movement of code to non-approved destinations is high risk.',
    60),
  ('business_function', 'bf_it',
    'IT',
    'IT operations, infrastructure, support, workplace technology, and systems teams.',
    'medium',
    'Handles system configurations, credentials, and infrastructure data. Admin-level access increases exposure risk.',
    70),
  ('business_function', 'bf_security',
    'Security',
    'Cybersecurity, SOC, GRC, incident response, vulnerability management, and data protection teams.',
    'high',
    'Handles security incidents, logs, forensic data, and DLP incidents. Exports outside approved systems require strong controls.',
    80),
  ('business_function', 'bf_operations',
    'Operations',
    'Business operations, logistics, service delivery, manufacturing, and process operations.',
    'low',
    'Handles operational reports and process documents. Unusual external sharing of logistics or operational data should be reviewed.',
    90),
  ('business_function', 'bf_procurement',
    'Procurement',
    'Procurement, vendor management, sourcing, and purchasing teams.',
    'medium',
    'Handles vendor contracts, purchase orders, and pricing agreements. Supplier data should not move to non-approved destinations.',
    100),
  ('business_function', 'bf_customer_support',
    'Customer Support',
    'Support, customer success, helpdesk, and service teams.',
    'medium',
    'Handles support tickets, customer cases, and troubleshooting logs. External transfer of case attachments requires monitoring.',
    110),
  ('business_function', 'bf_product',
    'Product',
    'Product management, product strategy, roadmap, and product operations.',
    'low',
    'Handles roadmaps, product requirements, and customer feedback. Roadmap sharing with external parties requires review.',
    120),
  ('business_function', 'bf_data_analytics',
    'Data / Analytics',
    'Data science, analytics, reporting, BI, and data platform teams.',
    'medium',
    'Handles datasets, models, and analytical extracts. Bulk data exports outside approved platforms are high risk.',
    130),
  ('business_function', 'bf_executive_leadership',
    'Executive / Leadership',
    'Executive, leadership, board, and senior management teams.',
    'high',
    'Handles board materials, strategy documents, and confidential financial summaries. External movement of strategic content is high risk.',
    140),
  ('business_function', 'bf_general_business_user',
    'General Business User',
    'User does not belong to a sensitive or specialised function.',
    'low',
    'General business documents and routine collaboration. Unexpected sensitive data movement should be reviewed.',
    150),
  ('business_function', 'bf_other',
    'Other / Customer Defined',
    'Customer-defined business function not covered by the standard list.',
    'low',
    'Risk depends on the customer-defined mapping and data access scope.',
    160)
ON CONFLICT (value_slug) DO NOTHING;

-- ─── Seed: Privilege Level (3 values) ────────────────────────────────────────

INSERT INTO catalog_identity_values
  (field_name, value_slug, value_name, description, risk_level, risk_note, priority)
VALUES
  ('privilege_level', 'pl_standard_user',
    'Standard User',
    'Normal business user with standard access to assigned applications and data.',
    'low',
    'Lower inherent risk due to limited access scope. Risk is determined by data type and destination.',
    10),
  ('privilege_level', 'pl_privileged_user',
    'Privileged User',
    'User with elevated access to sensitive systems, applications, data, or administrative functions.',
    'high',
    'Can access or move larger volumes of sensitive data. Exports and bulk transfers require stronger review.',
    20),
  ('privilege_level', 'pl_admin',
    'Admin',
    'User with administrative control over systems, applications, security tools, cloud platforms, identity, or data repositories.',
    'critical',
    'Can access data at scale, modify controls, and bypass restrictions. All sensitive data movement requires monitoring. Compromised admin accounts can create critical incidents.',
    30)
ON CONFLICT (value_slug) DO NOTHING;

-- ─── Seed: Employment Type (8 values) ────────────────────────────────────────

INSERT INTO catalog_identity_values
  (field_name, value_slug, value_name, description, risk_level, risk_note, priority)
VALUES
  ('employment_type', 'et_employee',
    'Employee',
    'Internal employee or regular workforce member.',
    'low',
    'Standard trust level. Risk is determined by data type, destination, and lifecycle status.',
    10),
  ('employment_type', 'et_contractor',
    'Contractor',
    'Temporary or contract worker engaged for a specific assignment.',
    'high',
    'Temporary access increases exfiltration risk. Sensitive data movement to personal or unknown destinations requires strong monitoring.',
    20),
  ('employment_type', 'et_vendor',
    'Vendor',
    'Third-party user associated with an external service provider or supplier.',
    'high',
    'Should only access data required for the approved service scope. Data movement outside that scope is high risk.',
    30),
  ('employment_type', 'et_intern',
    'Intern',
    'Short-term trainee, student, apprentice, or internship user.',
    'medium',
    'May lack business context and mishandle sensitive data. Bulk downloads and external sharing should be reviewed.',
    40),
  ('employment_type', 'et_partner_external',
    'Partner / External Collaborator',
    'External user collaborating under a business partnership.',
    'medium',
    'Access should be scoped to the collaboration context. Data movement outside the agreed scope requires review.',
    50),
  ('employment_type', 'et_service_non_human',
    'Service / Non-Human Identity',
    'Non-human identity used by systems, integrations, automation, or applications.',
    'critical',
    'Can move data at scale without human intent. Unexpected activity or credential exposure can create critical incidents. All service accounts should have an identified owner and approved scope.',
    60),
  ('employment_type', 'et_shared_account',
    'Shared Account',
    'Account used by multiple people or team members.',
    'high',
    'Reduces attribution and accountability. Investigations are harder. Shared accounts should be replaced or tagged for higher-risk monitoring.',
    70),
  ('employment_type', 'et_other',
    'Other / Customer Defined',
    'Customer-defined employment or identity relationship.',
    'low',
    'Risk depends on the customer-defined mapping and access scope.',
    80)
ON CONFLICT (value_slug) DO NOTHING;

-- ─── Seed: User Lifecycle Status (9 values) ──────────────────────────────────

INSERT INTO catalog_identity_values
  (field_name, value_slug, value_name, description, risk_level, risk_note, priority)
VALUES
  ('user_lifecycle_status', 'ls_active',
    'Active',
    'Normal active user with expected access.',
    'low',
    'Standard risk level. Risk determined by data type, channel, and destination.',
    10),
  ('user_lifecycle_status', 'ls_new_joiner',
    'New Joiner',
    'Recently joined user, still in onboarding or initial access period.',
    'medium',
    'May receive excessive access or lack business process understanding. Bulk downloads during onboarding should be reviewed.',
    20),
  ('user_lifecycle_status', 'ls_role_changed',
    'Role Changed',
    'User recently changed role, department, project, or access scope.',
    'high',
    'May retain access to data from previous role. Access drift and oversharing of old department data requires review.',
    30),
  ('user_lifecycle_status', 'ls_notice_period_leaver',
    'Notice Period / Leaver',
    'User is in resignation, offboarding, transition, or exit period.',
    'critical',
    'High exfiltration risk. Sensitive data movement — especially customer lists, source code, and financial data — must be monitored and alerted.',
    40),
  ('user_lifecycle_status', 'ls_suspended',
    'Suspended',
    'User access is temporarily disabled, restricted, or under investigation.',
    'critical',
    'Suspended users should not perform data movement. Any activity from a suspended account is a critical investigation priority.',
    50),
  ('user_lifecycle_status', 'ls_inactive',
    'Inactive',
    'Account has had no recent legitimate activity or appears dormant.',
    'high',
    'Dormant accounts that suddenly become active may indicate misuse or compromise. All data movement requires immediate review.',
    60),
  ('user_lifecycle_status', 'ls_terminated',
    'Terminated',
    'User is no longer employed or authorised, but account or activity still appears.',
    'critical',
    'Activity from terminated accounts indicates an access removal failure or account compromise. Critical access control gap.',
    70),
  ('user_lifecycle_status', 'ls_leave_of_absence',
    'Leave of Absence',
    'User is temporarily away from work.',
    'high',
    'Activity during extended absence may indicate account misuse or unexpected access by another person.',
    80),
  ('user_lifecycle_status', 'ls_unknown_lifecycle',
    'Unknown Lifecycle Status',
    'Lifecycle status is unavailable or not mapped.',
    'medium',
    'Missing lifecycle data reduces assessment accuracy. Organisations should integrate HR or IAM lifecycle feeds.',
    90)
ON CONFLICT (value_slug) DO NOTHING;
